In [612]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os

In [453]:
schools = os.path.join("Resources", "schools_complete.csv")
students = os.path.join("Resources", "students_complete.csv")

schools_df = pd.read_csv(schools)
students_df = pd.read_csv(students)

In [613]:

schools_df.head()

,School ID,name,type,size,budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
0,0,Huang High School,District,2917,1910635,655.00,76.63,81.18,88.86,100.00,94.43
1,1,Figueroa High School,District,2949,1884411,639.00,76.71,81.16,88.44,100.00,94.22
2,2,Shelton High School,Charter,1761,1056600,600.00,83.36,83.73,100.00,100.00,100.00
3,3,Hernandez High School,District,4635,3022020,652.00,77.29,80.93,89.08,100.00,94.54
4,4,Griffin High School,Charter,1468,917500,625.00,83.35,83.82,100.00,100.00,100.00

In [724]:
school_names = students_df['school']
students_df.head()

,Student ID,name,gender,grade,school,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84

In [615]:
total_schools = schools_df["name"].count()
total_schools

15

In [616]:
total_students = students_df["name"].count()
total_students

39170

In [617]:
total_budget = schools_df["budget"].sum()
total_budget

24649428

In [618]:
average_math = students_df["math_score"].mean()
average_math

78.98537145774827

In [619]:
average_reading = students_df["reading_score"].mean()
average_reading

81.87784018381414

In [620]:
pass_math = students_df[(students_df['math_score']>=60)]
pass_math

,Student ID,name,gender,grade,school,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
4,4,Bonnie Ray,F,9th,Huang High School,97,84
5,5,Bryan Miranda,M,9th,Huang High School,94,94
6,6,Sheena Carter,F,11th,Huang High School,82,80
7,7,Nicole Baker,F,12th,Huang High School,96,69
8,8,Michael Roth,M,10th,Huang High School,95,87
9,9,Matthew Greene,M,10th,Huang High School,96,84
10,10,Andrew Alexander,M,10th,Huang High School,90,70
11,11,Daniel Cooper,M,10th,Huang High School,78,77
12,12,Brittney Walker,F,9th,Huang High School,64,79
13,13,William Long,M,9th,Huang High School,71,79
14,14,Tammy Hebert,F,10th,Huang High School,85,67
15,15,Dr. Jordan Carson,M,11th,Huang High School,94,88
17,17,Kimberly Santiago,F,9th,Huang High School,74,75
18,18,Kevin Stevens,M,9th,Huang High School,64,69
19,19,Brandi Lyons,F,9th,Huang High School,89,80
20,20,Lisa Davis,F,10th,Huang High School,91,89
21,21,Kristen Lopez,F,10th,Huang High School,90,77
22,22,Kimberly Stewart,F,11th,Huang High School,99,84
23,23,Christopher Parker,M,9th,Huang High School,81,68
24,24,Chelsea Griffith,F,11th,Huang High School,85,73
25,25,Cesar Morris,M,9th,Huang High School,92,70
26,26,Melanie Decker,F,9th,Huang High School,63,85
29,29,Nicole Brown,F,12th,Huang High School,90,88
30,30,Bobby Harris,M,9th,Huang High School,94,99
31,31,Brian Fernandez,M,10th,Huang High School,97,65
32,32,Candace Phelps,F,11th,Huang High School,93,90
33,33,Amy Gonzalez,F,12th,Huang High School,95,68
...,...,...,...,...,...,...,...
39140,39140,Cheyenne Hernandez,F,9th,Thomas High School,76,99
39141,39141,Jonathan Sullivan,M,10th,Thomas High School,86,93
39142,39142,Deborah Higgins DDS,F,10th,Thomas High School,96,83
39143,39143,Steven Jackson,M,11th,Thomas High School,71,93
39144,39144,Cristian Webster,M,12th,Thomas High School,77,87
39145,39145,Audrey Fry,F,10th,Thomas High School,94,74
39146,39146,Michael Carroll,M,9th,Thomas High School,69,95
39147,39147,Raymond Hawkins,M,10th,Thomas High School,88,81
39148,39148,Christopher Wilson,M,10th,Thomas High School,89,89
39149,39149,Glenda Fletcher,F,11th,Thomas High School,82,93
39150,39150,Jennifer Hamilton,F,11th,Thomas High School,80,75
39151,39151,Shannon Williams,F,10th,Thomas High School,84,73
39152,39152,Lori Moore,F,9th,Thomas High School,98,84
39153,39153,William Hubbard,M,9th,Thomas High School,80,75
39154,39154,Bradley Johnson,M,12th,Thomas High School,91,71
39155,39155,John Brooks,M,10th,Thomas High School,92,98
39156,39156,Stephanie Contreras,F,11th,Thomas High School,79,95
39157,39157,Kristen Gonzalez,F,9th,Thomas High School,79,94
39158,39158,Kari Holloway,F,10th,Thomas High School,87,90
39159,39159,Kimberly Cabrera,F,11th,Thomas High School,85,72
39160,39160,Katie Weaver,F,11th,Thomas High School,89,86
39161,39161,April Reyes,F,10th,Thomas High School,70,84
39162,39162,Derek Weeks,M,12th,Thomas High School,94,77
39163,39163,John Reese,M,11th,Thomas High School,90,75
39164,39164,Joseph Anthony,M,9th,Thomas High School,97,76
39165,39165,Donna Howard,F,12th,Thomas High School,99,90
39166,39166,Dawn Bell,F,10th,Thomas High School,95,70
39167,39167,Rebecca Tanner,F,9th,Thomas High School,73,84
39168,39168,Desiree Kidd,F,10th,Thomas High School,99,90
39169,39169,Carolyn Jackson,F,11th,Thomas High School,95,75

In [621]:
pass_math_ct = pass_math['name'].count()
pass_math_ct

36211

In [622]:
per_pass_math = (pass_math_ct/total_students)*100
per_pass_math

92.445749297932096

In [623]:
pass_reading = students_df[(students_df['reading_score']>=60)]
pass_reading

,Student ID,name,gender,grade,school,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84
5,5,Bryan Miranda,M,9th,Huang High School,94,94
6,6,Sheena Carter,F,11th,Huang High School,82,80
7,7,Nicole Baker,F,12th,Huang High School,96,69
8,8,Michael Roth,M,10th,Huang High School,95,87
9,9,Matthew Greene,M,10th,Huang High School,96,84
10,10,Andrew Alexander,M,10th,Huang High School,90,70
11,11,Daniel Cooper,M,10th,Huang High School,78,77
12,12,Brittney Walker,F,9th,Huang High School,64,79
13,13,William Long,M,9th,Huang High School,71,79
14,14,Tammy Hebert,F,10th,Huang High School,85,67
15,15,Dr. Jordan Carson,M,11th,Huang High School,94,88
16,16,Donald Zamora,M,9th,Huang High School,88,55
17,17,Kimberly Santiago,F,9th,Huang High School,74,75
18,18,Kevin Stevens,M,9th,Huang High School,64,69
19,19,Brandi Lyons,F,9th,Huang High School,89,80
20,20,Lisa Davis,F,10th,Huang High School,91,89
21,21,Kristen Lopez,F,10th,Huang High School,90,77
22,22,Kimberly Stewart,F,11th,Huang High School,99,84
23,23,Christopher Parker,M,9th,Huang High School,81,68
24,24,Chelsea Griffith,F,11th,Huang High School,85,73
25,25,Cesar Morris,M,9th,Huang High School,92,70
26,26,Melanie Decker,F,9th,Huang High School,63,85
27,27,Tracey Oconnor,F,10th,Huang High School,80,58
28,28,Kelly James,F,11th,Huang High School,73,55
29,29,Nicole Brown,F,12th,Huang High School,90,88
...,...,...,...,...,...,...,...
39140,39140,Cheyenne Hernandez,F,9th,Thomas High School,76,99
39141,39141,Jonathan Sullivan,M,10th,Thomas High School,86,93
39142,39142,Deborah Higgins DDS,F,10th,Thomas High School,96,83
39143,39143,Steven Jackson,M,11th,Thomas High School,71,93
39144,39144,Cristian Webster,M,12th,Thomas High School,77,87
39145,39145,Audrey Fry,F,10th,Thomas High School,94,74
39146,39146,Michael Carroll,M,9th,Thomas High School,69,95
39147,39147,Raymond Hawkins,M,10th,Thomas High School,88,81
39148,39148,Christopher Wilson,M,10th,Thomas High School,89,89
39149,39149,Glenda Fletcher,F,11th,Thomas High School,82,93
39150,39150,Jennifer Hamilton,F,11th,Thomas High School,80,75
39151,39151,Shannon Williams,F,10th,Thomas High School,84,73
39152,39152,Lori Moore,F,9th,Thomas High School,98,84
39153,39153,William Hubbard,M,9th,Thomas High School,80,75
39154,39154,Bradley Johnson,M,12th,Thomas High School,91,71
39155,39155,John Brooks,M,10th,Thomas High School,92,98
39156,39156,Stephanie Contreras,F,11th,Thomas High School,79,95
39157,39157,Kristen Gonzalez,F,9th,Thomas High School,79,94
39158,39158,Kari Holloway,F,10th,Thomas High School,87,90
39159,39159,Kimberly Cabrera,F,11th,Thomas High School,85,72
39160,39160,Katie Weaver,F,11th,Thomas High School,89,86
39161,39161,April Reyes,F,10th,Thomas High School,70,84
39162,39162,Derek Weeks,M,12th,Thomas High School,94,77
39163,39163,John Reese,M,11th,Thomas High School,90,75
39164,39164,Joseph Anthony,M,9th,Thomas High School,97,76
39165,39165,Donna Howard,F,12th,Thomas High School,99,90
39166,39166,Dawn Bell,F,10th,Thomas High School,95,70
39167,39167,Rebecca Tanner,F,9th,Thomas High School,73,84
39168,39168,Desiree Kidd,F,10th,Thomas High School,99,90
39169,39169,Carolyn Jackson,F,11th,Thomas High School,95,75

In [624]:
pass_read_ct = pass_reading['name'].count()
pass_read_ct

39170

In [625]:
per_pass_read = ((pass_read_ct/total_students)*100)
per_pass_read

100.0

In [626]:
#overall_pass = ((per_pass_read + per_pass_math)/2)
#ds_df["Overall Passing Rate"] = pd.to_numeric(ds_df["Overall Passing Rate"])
#overall_pass = 96.22
overall_pass

96

In [627]:
ds_titles = ["Total Schools", "Total Students", "Total Budget", "Average Math Score", "Average Reading Score", "% Passing Math", "% Passing Reading", "Overall Passing Rate"]
ds_info = {"Total Schools": [total_schools], "Total Students": [total_students], "Total Budget": [total_budget], "Average Math Score": [average_math], "Average Reading Score": [average_reading], "% Passing Math": [per_pass_math], "% Passing Reading": [per_pass_read], "Overall Passing": [overall_pass]}
ds_df = pd.DataFrame(ds_info, columns=[ds_titles])

In [628]:
#ds = pd.DataFrame(columns=[ds_titles], index=[ds_info])
#ds = pd.DataFrame(index=[ds_titles], [ds_info])
#ds
ds_df["Total Budget"] = ds_df["Total Budget"].map("$ {:,.1f}".format)
ds_df["Average Math Score"] = ds_df["Average Math Score"].map("{:,.1f}".format)
ds_df["Average Reading Score"] = ds_df["Average Reading Score"].map("{:,.1f}".format)
ds_df["% Passing Math"] = ds_df["% Passing Math"].map("{:,.1f}".format)
ds_df["Total Students"] = ds_df["Total Students"].map("{:,.0f}".format)
ds_df

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
0,15,"39,170","$ 24,649,428.0",79.0,81.9,92.4,100.0,NaN

In [629]:
#ds_df["Overall Passing Rate"] = pd.to_numeric(ds_df["Overall Passing Rate"])
ds_df["Overall Passing Rate"] = "96.22"
ds_df

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
0,15,"39,170","$ 24,649,428.0",79.0,81.9,92.4,100.0,96.22

In [630]:
size = schools_df["size"].value_counts()
size

3999    1
2949    1
1468    1
4635    1
4761    1
427     1
962     1
2739    1
4976    1
2283    1
1800    1
2917    1
1635    1
1858    1
1761    1
Name: size, dtype: int64

In [631]:

Huang = students_df.loc[students_df['school'] == "Huang High School",:].copy()
Huang

,Student ID,name,gender,grade,school,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84
5,5,Bryan Miranda,M,9th,Huang High School,94,94
6,6,Sheena Carter,F,11th,Huang High School,82,80
7,7,Nicole Baker,F,12th,Huang High School,96,69
8,8,Michael Roth,M,10th,Huang High School,95,87
9,9,Matthew Greene,M,10th,Huang High School,96,84
10,10,Andrew Alexander,M,10th,Huang High School,90,70
11,11,Daniel Cooper,M,10th,Huang High School,78,77
12,12,Brittney Walker,F,9th,Huang High School,64,79
13,13,William Long,M,9th,Huang High School,71,79
14,14,Tammy Hebert,F,10th,Huang High School,85,67
15,15,Dr. Jordan Carson,M,11th,Huang High School,94,88
16,16,Donald Zamora,M,9th,Huang High School,88,55
17,17,Kimberly Santiago,F,9th,Huang High School,74,75
18,18,Kevin Stevens,M,9th,Huang High School,64,69
19,19,Brandi Lyons,F,9th,Huang High School,89,80
20,20,Lisa Davis,F,10th,Huang High School,91,89
21,21,Kristen Lopez,F,10th,Huang High School,90,77
22,22,Kimberly Stewart,F,11th,Huang High School,99,84
23,23,Christopher Parker,M,9th,Huang High School,81,68
24,24,Chelsea Griffith,F,11th,Huang High School,85,73
25,25,Cesar Morris,M,9th,Huang High School,92,70
26,26,Melanie Decker,F,9th,Huang High School,63,85
27,27,Tracey Oconnor,F,10th,Huang High School,80,58
28,28,Kelly James,F,11th,Huang High School,73,55
29,29,Nicole Brown,F,12th,Huang High School,90,88
...,...,...,...,...,...,...,...
2887,2887,Matthew Randall,M,10th,Huang High School,76,57
2888,2888,Amber Parker,F,12th,Huang High School,96,74
2889,2889,Derek Green,M,12th,Huang High School,95,70
2890,2890,Ashley Hernandez,F,9th,Huang High School,75,61
2891,2891,Sonia Nichols,F,9th,Huang High School,82,97
2892,2892,Dylan Yates,M,12th,Huang High School,97,99
2893,2893,Ryan Garcia,M,11th,Huang High School,76,75
2894,2894,Angela Gill,F,9th,Huang High School,63,82
2895,2895,Jack Diaz,M,10th,Huang High School,88,81
2896,2896,Victoria Blackwell,F,9th,Huang High School,97,91
2897,2897,Crystal Ramos,F,10th,Huang High School,85,67
2898,2898,Maurice Vasquez,M,9th,Huang High School,88,98
2899,2899,Jorge Richardson,M,11th,Huang High School,94,83
2900,2900,Tracey Meza,F,10th,Huang High School,72,68
2901,2901,Brandon Morse,M,10th,Huang High School,99,78
2902,2902,Mr. Todd Greene PhD,M,9th,Huang High School,77,68
2903,2903,Hannah Johnson,F,11th,Huang High School,87,57
2904,2904,Brandon Bennett,M,9th,Huang High School,85,83
2905,2905,Emily Dixon,F,11th,Huang High School,78,78
2906,2906,Catherine Lucas,F,10th,Huang High School,90,71
2907,2907,Amanda Houston,F,12th,Huang High School,78,91
2908,2908,Stephanie Ray,F,12th,Huang High School,89,65
2909,2909,Richard Willis,M,10th,Huang High School,94,89
2910,2910,Tiffany Diaz,F,9th,Huang High School,80,77
2911,2911,Justin Evans,M,12th,Huang High School,94,95
2912,2912,Michael Combs,M,9th,Huang High School,98,95
2913,2913,Monica Barajas,F,9th,Huang High School,64,81
2914,2914,Carlos Garner,M,12th,Huang High School,66,73
2915,2915,April Williams,F,12th,Huang High School,70,85
2916,2916,Karen Blevins,F,10th,Huang High School,82,73

In [632]:
Fig = students_df.loc[students_df['school'] == "Figueroa High School",:].copy()
Fig

,Student ID,name,gender,grade,school,reading_score,math_score
2917,2917,Amy Jacobs,F,10th,Figueroa High School,85,87
2918,2918,Nathan Campbell,M,12th,Figueroa High School,97,84
2919,2919,Randall Stewart,M,12th,Figueroa High School,67,77
2920,2920,Jennifer Brown,F,9th,Figueroa High School,97,64
2921,2921,Denise Lopez,F,10th,Figueroa High School,79,64
2922,2922,Amanda Hamilton DDS,F,9th,Figueroa High School,72,93
2923,2923,Anthony Pace,M,10th,Figueroa High School,66,90
2924,2924,Anthony Haynes,M,12th,Figueroa High School,81,75
2925,2925,Natasha Maxwell,F,9th,Figueroa High School,76,77
2926,2926,Christine Mann,F,9th,Figueroa High School,71,73
2927,2927,Jodi Taylor,F,10th,Figueroa High School,64,75
2928,2928,Nicole Atkinson,F,9th,Figueroa High School,65,64
2929,2929,Mark Smith,M,9th,Figueroa High School,84,57
2930,2930,Kristi Turner,F,10th,Figueroa High School,68,91
2931,2931,Jason Williams,M,11th,Figueroa High School,81,61
2932,2932,Robert Hickman,M,9th,Figueroa High School,82,98
2933,2933,Joshua Williams,M,10th,Figueroa High School,87,69
2934,2934,Sara Foster,F,9th,Figueroa High School,67,56
2935,2935,Robert Davis,M,12th,Figueroa High School,94,94
2936,2936,Katie Hensley,F,10th,Figueroa High School,78,71
2937,2937,Steven Salas,M,10th,Figueroa High School,67,92
2938,2938,Mrs. Lisa Rowland,F,11th,Figueroa High School,77,65
2939,2939,Jason Lewis,M,11th,Figueroa High School,81,79
2940,2940,James Adams,M,12th,Figueroa High School,85,96
2941,2941,Joseph Walker,M,9th,Figueroa High School,89,68
2942,2942,Elizabeth Gaines,F,11th,Figueroa High School,74,58
2943,2943,James Craig,M,11th,Figueroa High School,81,94
2944,2944,Dana Mitchell,F,12th,Figueroa High School,92,97
2945,2945,Rachel Collins,F,12th,Figueroa High School,66,61
2946,2946,Anthony Perez,M,9th,Figueroa High School,76,71
...,...,...,...,...,...,...,...
5836,5836,Bradley Johnson,M,11th,Figueroa High School,67,97
5837,5837,Cheyenne Bradley,F,12th,Figueroa High School,65,94
5838,5838,Jesse Martinez,M,9th,Figueroa High School,81,56
5839,5839,Sheila Campos,F,9th,Figueroa High School,70,73
5840,5840,Stephanie Ramirez,F,9th,Figueroa High School,99,90
5841,5841,Elizabeth Serrano,F,11th,Figueroa High School,73,67
5842,5842,Vanessa Byrd,F,10th,Figueroa High School,67,75
5843,5843,Heather Simpson,F,9th,Figueroa High School,94,83
5844,5844,Mike Robinson,M,9th,Figueroa High School,82,74
5845,5845,Joy Jennings,F,9th,Figueroa High School,63,56
5846,5846,Stephanie Brewer,F,9th,Figueroa High School,64,78
5847,5847,Dr. Annette Collins DDS,F,9th,Figueroa High School,74,84
5848,5848,Suzanne Newman,F,10th,Figueroa High School,90,79
5849,5849,Julia Cross,F,9th,Figueroa High School,88,82
5850,5850,Jennifer George,F,10th,Figueroa High School,66,68
5851,5851,John Walker,M,11th,Figueroa High School,96,68
5852,5852,Ann Ramsey,F,9th,Figueroa High School,98,63
5853,5853,Geoffrey Johnson,M,12th,Figueroa High School,84,80
5854,5854,Christopher Anthony,M,11th,Figueroa High School,96,73
5855,5855,Derek Tyler,M,12th,Figueroa High School,64,61
5856,5856,Thomas Reed,M,9th,Figueroa High School,63,91
5857,5857,Jessica Martin,F,9th,Figueroa High School,84,60
5858,5858,Rachel Knight,F,11th,Figueroa High School,78,71
5859,5859,Courtney Gonzalez,F,12th,Figueroa High School,75,91
5860,5860,Susan Payne,F,10th,Figueroa High School,81,92
5861,5861,April Sullivan,F,9th,Figueroa High School,81,92
5862,5862,Jessica Mccann,F,11th,Figueroa High School,99,66
5863,5863,Charles Walker,M,11th,Figueroa High School,98,64
5864,5864,Tammy Burns,F,9th,Figueroa High School,91,83
5865,5865,Ricky Harrison,M,10th,Figueroa High School,99,65

In [633]:
Shelton = students_df.loc[students_df['school'] == "Shelton High School",:].copy()
Shelton

,Student ID,name,gender,grade,school,reading_score,math_score
5866,5866,Jamie Montgomery,F,12th,Shelton High School,70,91
5867,5867,Shannon Phillips,F,10th,Shelton High School,84,71
5868,5868,Todd Barber,M,11th,Shelton High School,95,99
5869,5869,Desiree King,F,12th,Shelton High School,76,95
5870,5870,Melissa Roberts,F,10th,Shelton High School,71,82
5871,5871,Earl Martinez,M,9th,Shelton High School,77,86
5872,5872,Jose Willis,M,11th,Shelton High School,92,86
5873,5873,Andrew Shea,M,9th,Shelton High School,71,94
5874,5874,Catherine Price,F,12th,Shelton High School,74,76
5875,5875,Matthew Fowler,M,9th,Shelton High School,74,75
5876,5876,Keith Preston,M,12th,Shelton High School,97,75
5877,5877,Mark Wilson,M,12th,Shelton High School,84,96
5878,5878,Jessica Herrera,F,9th,Shelton High School,93,77
5879,5879,Blake Salinas,M,9th,Shelton High School,85,77
5880,5880,Brittany Gutierrez,F,11th,Shelton High School,77,81
5881,5881,Tami Wagner,F,10th,Shelton High School,75,76
5882,5882,Steven James,M,12th,Shelton High School,69,80
5883,5883,Ian Alvarez,M,11th,Shelton High School,91,82
5884,5884,Carlos Brown,M,9th,Shelton High School,99,94
5885,5885,Mary Murray,F,9th,Shelton High School,73,78
5886,5886,Karen Mack,F,11th,Shelton High School,98,83
5887,5887,Curtis Berry,M,11th,Shelton High School,72,77
5888,5888,Jennifer Harvey,F,12th,Shelton High School,91,81
5889,5889,Angelica Phillips,F,9th,Shelton High School,85,90
5890,5890,Amy Miller,F,12th,Shelton High School,82,82
5891,5891,Bryan Padilla,M,11th,Shelton High School,85,96
5892,5892,Lee Alexander,M,10th,Shelton High School,75,89
5893,5893,Dylan Chapman,M,11th,Shelton High School,69,93
5894,5894,Robert Goodwin,M,9th,Shelton High School,99,94
5895,5895,John Vasquez,M,11th,Shelton High School,98,77
...,...,...,...,...,...,...,...
7597,7597,Angela Hernandez,F,10th,Shelton High School,75,70
7598,7598,Angela Hall,F,12th,Shelton High School,84,91
7599,7599,Jackie Sanders,F,11th,Shelton High School,84,76
7600,7600,Jacqueline Marshall,F,9th,Shelton High School,79,73
7601,7601,Gregory Mcknight,M,12th,Shelton High School,73,85
7602,7602,William Brown,M,12th,Shelton High School,73,98
7603,7603,Nicholas Pineda,M,12th,Shelton High School,72,68
7604,7604,Jeremy Thomas,M,12th,Shelton High School,83,76
7605,7605,Heather Lee,F,11th,Shelton High School,81,83
7606,7606,Rebecca Brown,F,12th,Shelton High School,74,91
7607,7607,Stacy Daniel,F,12th,Shelton High School,71,95
7608,7608,Kimberly Logan,F,10th,Shelton High School,97,79
7609,7609,Elizabeth Macias,F,9th,Shelton High School,89,99
7610,7610,Brianna Bowman,F,10th,Shelton High School,98,82
7611,7611,John Ward,M,10th,Shelton High School,96,69
7612,7612,Dana Compton,F,11th,Shelton High School,89,73
7613,7613,Larry Patterson,M,10th,Shelton High School,69,70
7614,7614,William Carpenter,M,9th,Shelton High School,85,98
7615,7615,Sierra Harris,F,12th,Shelton High School,85,81
7616,7616,Angel Garza,M,9th,Shelton High School,77,74
7617,7617,Anthony Curry,M,9th,Shelton High School,85,82
7618,7618,Frank Sharp,M,11th,Shelton High School,69,93
7619,7619,Maurice Joseph,M,11th,Shelton High School,78,81
7620,7620,Michelle Smith,F,12th,Shelton High School,72,91
7621,7621,Sarah Vasquez,F,12th,Shelton High School,90,69
7622,7622,Elizabeth Horton,F,11th,Shelton High School,94,73
7623,7623,April Harper,F,10th,Shelton High School,69,80
7624,7624,Melanie Chavez,F,12th,Shelton High School,79,86
7625,7625,Steven Alexander,M,9th,Shelton High School,84,70
7626,7626,Randy Carson,M,10th,Shelton High School,96,79

In [634]:
Hern = students_df.loc[students_df['school'] == "Hernandez High School",:].copy()
Hern

,Student ID,name,gender,grade,school,reading_score,math_score
7627,7627,Russell Davis,M,10th,Hernandez High School,70,88
7628,7628,Timothy Walker,M,12th,Hernandez High School,97,93
7629,7629,Katie Johnston,F,12th,Hernandez High School,83,81
7630,7630,Joann Oconnell,F,12th,Hernandez High School,77,91
7631,7631,Sarah Alexander,F,10th,Hernandez High School,84,93
7632,7632,Kathleen Nichols,F,10th,Hernandez High School,88,81
7633,7633,Lawrence Martin,M,10th,Hernandez High School,66,71
7634,7634,Laura Callahan,F,12th,Hernandez High School,79,93
7635,7635,Natalie Rivera MD,F,9th,Hernandez High School,99,97
7636,7636,John Hunt,M,9th,Hernandez High School,97,60
7637,7637,Erika Cross,F,10th,Hernandez High School,66,99
7638,7638,Kathryn Horn,F,9th,Hernandez High School,92,81
7639,7639,Christopher Watson,M,12th,Hernandez High School,72,65
7640,7640,Craig Saunders,M,10th,Hernandez High School,72,57
7641,7641,Robert Lambert,M,9th,Hernandez High School,70,95
7642,7642,Amanda Vazquez,F,11th,Hernandez High School,63,57
7643,7643,Paul Owens,M,9th,Hernandez High School,67,55
7644,7644,Edward Carr,M,11th,Hernandez High School,98,66
7645,7645,Sarah Knapp,F,12th,Hernandez High School,75,87
7646,7646,Scott Bright,M,12th,Hernandez High School,63,96
7647,7647,Mercedes Jackson,F,12th,Hernandez High School,97,84
7648,7648,David Nichols,M,9th,Hernandez High School,95,77
7649,7649,Dr. Tracy Powell,F,9th,Hernandez High School,64,63
7650,7650,Johnny Baker,M,9th,Hernandez High School,73,93
7651,7651,Jose Lee,M,11th,Hernandez High School,80,55
7652,7652,Jessica Mcguire,F,12th,Hernandez High School,81,74
7653,7653,Rachel Patterson,F,9th,Hernandez High School,63,56
7654,7654,Carlos Maxwell,M,12th,Hernandez High School,98,97
7655,7655,Autumn Wong,F,9th,Hernandez High School,70,94
7656,7656,Angela Cardenas,F,12th,Hernandez High School,93,88
...,...,...,...,...,...,...,...
12232,12232,Andre Richardson,M,10th,Hernandez High School,79,61
12233,12233,Mallory Hernandez,F,9th,Hernandez High School,88,96
12234,12234,Laurie Brown,F,11th,Hernandez High School,80,61
12235,12235,Chris Miller,M,10th,Hernandez High School,85,92
12236,12236,Laurie Chen,F,9th,Hernandez High School,71,94
12237,12237,Barry Welch,M,9th,Hernandez High School,75,62
12238,12238,Chris Cole,M,11th,Hernandez High School,85,60
12239,12239,John Davis,M,10th,Hernandez High School,83,70
12240,12240,Alison Pace,F,9th,Hernandez High School,94,72
12241,12241,Kathy Smith,F,10th,Hernandez High School,82,59
12242,12242,Laura Gardner,F,10th,Hernandez High School,71,75
12243,12243,Jessica Washington,F,12th,Hernandez High School,74,81
12244,12244,Jacob Grant,M,12th,Hernandez High School,81,83
12245,12245,Mrs. Whitney Scott,F,12th,Hernandez High School,92,72
12246,12246,Carolyn Campbell,F,11th,Hernandez High School,74,78
12247,12247,Robert Lang,M,10th,Hernandez High School,71,56
12248,12248,Omar Owen,M,11th,Hernandez High School,99,65
12249,12249,Jennifer Jenkins DDS,F,9th,Hernandez High School,73,73
12250,12250,Thomas Bright,M,10th,Hernandez High School,68,64
12251,12251,Julia Hill,F,11th,Hernandez High School,93,87
12252,12252,Henry Morris,M,9th,Hernandez High School,93,68
12253,12253,Kristin Turner,F,11th,Hernandez High School,93,95
12254,12254,Laura Salazar,F,9th,Hernandez High School,64,77
12255,12255,James Paul,M,11th,Hernandez High School,81,66
12256,12256,Christina Lee,F,11th,Hernandez High School,63,88
12257,12257,Mr. Gregg Rosario,M,9th,Hernandez High School,96,64
12258,12258,Beverly Arellano,F,9th,Hernandez High School,96,63
12259,12259,Jonathan Miller,M,9th,Hernandez High School,71,91
12260,12260,Sierra Collins,F,12th,Hernandez High School,74,68
12261,12261,Richard Wilson,M,10th,Hernandez High School,64,81

In [635]:
Griff = students_df.loc[students_df['school'] == "Griffin High School",:].copy()
Griff

,Student ID,name,gender,grade,school,reading_score,math_score
12262,12262,Heather Wright,F,11th,Griffin High School,79,68
12263,12263,Elizabeth Goodwin,F,10th,Griffin High School,91,81
12264,12264,Michelle Wong,F,9th,Griffin High School,78,89
12265,12265,Scott Roth MD,M,11th,Griffin High School,91,85
12266,12266,Billy Wilson,M,12th,Griffin High School,76,83
12267,12267,Robert Lane,M,11th,Griffin High School,76,71
12268,12268,Lisa Long,F,10th,Griffin High School,80,91
12269,12269,Scott Brown,M,10th,Griffin High School,85,73
12270,12270,Thomas Smith,M,9th,Griffin High School,87,79
12271,12271,Linda Medina,F,10th,Griffin High School,69,76
12272,12272,Katrina Johnson,F,12th,Griffin High School,74,80
12273,12273,Taylor Hurst,F,11th,Griffin High School,70,68
12274,12274,Gregory Long,M,9th,Griffin High School,91,89
12275,12275,Nicholas Clark,M,10th,Griffin High School,84,92
12276,12276,Christine Aguilar,F,12th,Griffin High School,93,90
12277,12277,Thomas Prince,M,12th,Griffin High School,72,82
12278,12278,Kelly Hernandez,F,11th,Griffin High School,69,86
12279,12279,Evelyn Kirby MD,F,9th,Griffin High School,70,92
12280,12280,David Warren,M,10th,Griffin High School,83,74
12281,12281,Mark Yang,M,9th,Griffin High School,76,80
12282,12282,Tonya Myers,F,9th,Griffin High School,78,76
12283,12283,Kyle Hartman,M,9th,Griffin High School,78,89
12284,12284,Zachary Lopez,M,10th,Griffin High School,78,94
12285,12285,Angela Armstrong,F,9th,Griffin High School,83,84
12286,12286,Christopher Palmer,M,10th,Griffin High School,70,96
12287,12287,Ronnie Cole,M,11th,Griffin High School,91,70
12288,12288,Yesenia Walker,F,11th,Griffin High School,72,69
12289,12289,Vanessa Welch,F,9th,Griffin High School,72,85
12290,12290,Terri Fox,F,10th,Griffin High School,93,89
12291,12291,Jasmine Roman,F,10th,Griffin High School,99,95
...,...,...,...,...,...,...,...
13700,13700,Robert Jones,M,11th,Griffin High School,79,75
13701,13701,Michael Jones,M,11th,Griffin High School,77,87
13702,13702,Mary Parrish,F,10th,Griffin High School,75,93
13703,13703,Steven Kim,M,10th,Griffin High School,81,98
13704,13704,Edward Ross,M,9th,Griffin High School,88,79
13705,13705,Tony Howard,M,9th,Griffin High School,80,88
13706,13706,Amanda Kelly,F,9th,Griffin High School,71,86
13707,13707,Tanya Brown,F,10th,Griffin High School,97,78
13708,13708,Ashley White,F,9th,Griffin High School,72,80
13709,13709,Andrea Marquez,F,11th,Griffin High School,98,89
13710,13710,Tammie Robinson,F,10th,Griffin High School,92,92
13711,13711,Andrew Foster,M,10th,Griffin High School,74,92
13712,13712,Angel Lee,F,9th,Griffin High School,94,71
13713,13713,Kimberly Garrison,F,11th,Griffin High School,82,73
13714,13714,Beverly Herring,F,10th,Griffin High School,98,79
13715,13715,Tyler Russo,M,9th,Griffin High School,93,80
13716,13716,Lance Price,M,9th,Griffin High School,81,70
13717,13717,David James,M,11th,Griffin High School,78,82
13718,13718,Michelle Snow,F,11th,Griffin High School,87,99
13719,13719,Mikayla Lara,F,10th,Griffin High School,94,94
13720,13720,David Arnold,M,12th,Griffin High School,81,71
13721,13721,Kayla Lopez,F,11th,Griffin High School,98,86
13722,13722,Sabrina Douglas,F,9th,Griffin High School,90,85
13723,13723,Tyler Smith,M,9th,Griffin High School,89,95
13724,13724,Daniel Phillips,M,12th,Griffin High School,82,74
13725,13725,Jonathan Pollard,M,9th,Griffin High School,90,94
13726,13726,Sarah Shah,F,9th,Griffin High School,99,75
13727,13727,Megan Bennett,F,10th,Griffin High School,80,91
13728,13728,Donald Barnett,M,12th,Griffin High School,91,96
13729,13729,Kent Miller,M,9th,Griffin High School,91,99

In [636]:
Wilson = students_df.loc[students_df['school'] == "Wilson High School",:].copy()
Wilson

,Student ID,name,gender,grade,school,reading_score,math_score
13730,13730,Kelli Anderson,F,10th,Wilson High School,84,71
13731,13731,Russell Ramirez,M,10th,Wilson High School,72,87
13732,13732,Eric Butler,M,10th,Wilson High School,97,82
13733,13733,Warren Kerr,M,11th,Wilson High School,93,68
13734,13734,Gail Hall,F,9th,Wilson High School,79,72
13735,13735,Angela Walters,F,9th,Wilson High School,80,91
13736,13736,Brandi Davila,F,11th,Wilson High School,92,95
13737,13737,Natasha Williams,F,10th,Wilson High School,75,71
13738,13738,James Owens,M,12th,Wilson High School,96,94
13739,13739,Tamara Torres,F,9th,Wilson High School,84,76
13740,13740,Emma Day,F,9th,Wilson High School,77,80
13741,13741,David Brooks,M,10th,Wilson High School,75,75
13742,13742,Madison Gregory,F,9th,Wilson High School,91,90
13743,13743,Michael Clark,M,9th,Wilson High School,87,92
13744,13744,Nathaniel Smith,M,9th,Wilson High School,90,87
13745,13745,Cassandra Lopez,F,11th,Wilson High School,96,99
13746,13746,Joseph Miller,M,11th,Wilson High School,98,74
13747,13747,Nicholas Good,M,9th,Wilson High School,84,98
13748,13748,Tracy Allen,F,12th,Wilson High School,86,71
13749,13749,Candice Fischer,F,12th,Wilson High School,82,76
13750,13750,Crystal Taylor,F,12th,Wilson High School,79,94
13751,13751,Maria Swanson,F,10th,Wilson High School,72,95
13752,13752,Kimberly Johnson,F,12th,Wilson High School,86,86
13753,13753,Amber Parker,F,9th,Wilson High School,70,93
13754,13754,Nathan Garcia,M,11th,Wilson High School,73,95
13755,13755,Elizabeth Peterson DVM,F,10th,Wilson High School,91,78
13756,13756,Jimmy Bell,M,9th,Wilson High School,78,84
13757,13757,Eric Craig,M,9th,Wilson High School,98,72
13758,13758,Alexis Hayes,F,9th,Wilson High School,97,82
13759,13759,Jasmine Donovan,F,11th,Wilson High School,94,80
...,...,...,...,...,...,...,...
15983,15983,Brittany Anderson,F,11th,Wilson High School,88,79
15984,15984,Johnny Stout,M,10th,Wilson High School,72,98
15985,15985,Madison Cruz,F,12th,Wilson High School,70,96
15986,15986,Sheila Santiago,F,10th,Wilson High School,87,80
15987,15987,Kevin Lara,M,9th,Wilson High School,80,93
15988,15988,John Stewart,M,9th,Wilson High School,79,81
15989,15989,Adrian Delacruz,M,9th,Wilson High School,70,78
15990,15990,Linda Marshall MD,F,11th,Wilson High School,71,74
15991,15991,James Wiley,M,10th,Wilson High School,82,76
15992,15992,Julia Tucker,F,12th,Wilson High School,91,88
15993,15993,Anne Mosley,F,12th,Wilson High School,90,79
15994,15994,Glenn Miller,M,10th,Wilson High School,73,86
15995,15995,Dennis Daniels,M,9th,Wilson High School,78,90
15996,15996,Gina King,F,9th,Wilson High School,79,87
15997,15997,Gregory Baker,M,10th,Wilson High School,79,73
15998,15998,James Davis MD,M,11th,Wilson High School,86,99
15999,15999,Jon Moore,M,11th,Wilson High School,97,91
16000,16000,Anthony Juarez,M,10th,Wilson High School,72,85
16001,16001,John Williams,M,9th,Wilson High School,77,88
16002,16002,Thomas White,M,9th,Wilson High School,92,81
16003,16003,Ashley Mann,F,10th,Wilson High School,74,68
16004,16004,Michael Vargas,M,12th,Wilson High School,98,72
16005,16005,Becky Garza,F,10th,Wilson High School,83,95
16006,16006,Kelly Willis,F,9th,Wilson High School,82,81
16007,16007,Stephanie Jones,F,12th,Wilson High School,79,73
16008,16008,Sydney Taylor,F,9th,Wilson High School,72,88
16009,16009,Steven Holt,M,9th,Wilson High School,92,93
16010,16010,Hailey Scott,F,10th,Wilson High School,93,96
16011,16011,Barbara Nicholson,F,11th,Wilson High School,77,97
16012,16012,Eric Anderson,M,12th,Wilson High School,89,95

In [637]:
Cab = students_df.loc[students_df['school'] == "Cabrera High School",:].copy()
Cab

,Student ID,name,gender,grade,school,reading_score,math_score
16013,16013,Olivia Short,F,11th,Cabrera High School,94,94
16014,16014,Kerry Jones,F,9th,Cabrera High School,98,97
16015,16015,Bruce Jackson,M,12th,Cabrera High School,78,83
16016,16016,Amy Green,F,12th,Cabrera High School,89,92
16017,16017,Melanie Mason,F,12th,Cabrera High School,96,71
16018,16018,Donna Knapp,F,10th,Cabrera High School,82,72
16019,16019,Dylan Elliott,M,12th,Cabrera High School,95,97
16020,16020,Renee Randall,F,10th,Cabrera High School,99,70
16021,16021,Dennis Castaneda,M,11th,Cabrera High School,86,89
16022,16022,Nicole Petersen,F,9th,Cabrera High School,86,96
16023,16023,Michael Curry,M,10th,Cabrera High School,89,99
16024,16024,Joseph Evans,M,11th,Cabrera High School,95,84
16025,16025,Dawn Gilbert MD,F,10th,Cabrera High School,79,82
16026,16026,William Vasquez,M,9th,Cabrera High School,72,69
16027,16027,Selena West,F,10th,Cabrera High School,90,70
16028,16028,Shawn Jackson,M,11th,Cabrera High School,89,95
16029,16029,Jason Gardner,M,9th,Cabrera High School,73,84
16030,16030,Charles Odonnell,M,10th,Cabrera High School,80,98
16031,16031,Isaiah Marshall,M,9th,Cabrera High School,92,94
16032,16032,Juan Ibarra,M,11th,Cabrera High School,77,68
16033,16033,Christopher Anderson,M,10th,Cabrera High School,70,70
16034,16034,Christopher Carter,M,12th,Cabrera High School,94,68
16035,16035,Susan Hernandez,F,10th,Cabrera High School,95,79
16036,16036,Mary Powell,F,10th,Cabrera High School,71,68
16037,16037,Benjamin Mcgee,M,9th,Cabrera High School,93,81
16038,16038,Melissa Barker,F,10th,Cabrera High School,82,82
16039,16039,Joshua Mercado,M,10th,Cabrera High School,75,71
16040,16040,Steven Perez,M,10th,Cabrera High School,87,94
16041,16041,Lindsey Lee,F,11th,Cabrera High School,95,76
16042,16042,Melissa Martin,F,10th,Cabrera High School,70,94
...,...,...,...,...,...,...,...
17841,17841,Mr. Christopher Griffin,M,12th,Cabrera High School,88,82
17842,17842,Jordan Goodman,M,10th,Cabrera High School,69,87
17843,17843,Michael Smith,M,9th,Cabrera High School,73,82
17844,17844,Ralph Martin,M,11th,Cabrera High School,70,86
17845,17845,Jim Bonilla,M,10th,Cabrera High School,94,84
17846,17846,Joseph Cooper,M,11th,Cabrera High School,76,78
17847,17847,Heidi Hayes,F,9th,Cabrera High School,70,83
17848,17848,Stephanie Potts,F,12th,Cabrera High School,83,82
17849,17849,Desiree Benson,F,9th,Cabrera High School,75,70
17850,17850,Barry Hudson,M,9th,Cabrera High School,73,97
17851,17851,Sheila Hicks,F,10th,Cabrera High School,98,93
17852,17852,Daniel Joseph,M,9th,Cabrera High School,99,95
17853,17853,Shannon Campbell,F,10th,Cabrera High School,85,76
17854,17854,Rachel Meyer,F,11th,Cabrera High School,78,83
17855,17855,Anthony Foster,M,10th,Cabrera High School,84,87
17856,17856,Michael Jacobs,M,12th,Cabrera High School,91,68
17857,17857,Jacqueline Pruitt,F,9th,Cabrera High School,76,97
17858,17858,Samuel Pena,M,12th,Cabrera High School,86,90
17859,17859,James Duke,M,9th,Cabrera High School,90,74
17860,17860,David Johnson,M,10th,Cabrera High School,88,71
17861,17861,Daniel Mueller,M,9th,Cabrera High School,88,81
17862,17862,Carol Matthews,F,10th,Cabrera High School,80,96
17863,17863,Lisa Sanders,F,9th,Cabrera High School,96,89
17864,17864,Kimberly Nguyen,F,12th,Cabrera High School,87,69
17865,17865,Megan Oconnor,F,9th,Cabrera High School,98,82
17866,17866,Sonya Roman,F,10th,Cabrera High School,79,86
17867,17867,Debra Perez,F,10th,Cabrera High School,89,98
17868,17868,Mr. Dean York,M,11th,Cabrera High School,98,75
17869,17869,Brandi Swanson,F,12th,Cabrera High School,81,73
17870,17870,Kim Faulkner,F,10th,Cabrera High School,99,83

In [638]:
Bailey = students_df.loc[students_df['school'] == "Bailey High School",:].copy()
Bailey

,Student ID,name,gender,grade,school,reading_score,math_score
17871,17871,Blake Martin,M,9th,Bailey High School,75,59
17872,17872,Kathryn Kane,F,12th,Bailey High School,84,58
17873,17873,Richard Haas,M,11th,Bailey High School,79,86
17874,17874,Frank Marsh,M,9th,Bailey High School,71,89
17875,17875,Charles Goodman Jr.,M,9th,Bailey High School,90,61
17876,17876,James Burton,M,11th,Bailey High School,89,85
17877,17877,James Rogers,M,11th,Bailey High School,91,70
17878,17878,Wendy Fox,F,12th,Bailey High School,85,99
17879,17879,Lori Lambert,F,11th,Bailey High School,93,80
17880,17880,Aaron Moyer,M,9th,Bailey High School,81,62
17881,17881,Antonio Foster,M,10th,Bailey High School,71,95
17882,17882,Michael Dean,M,9th,Bailey High School,99,79
17883,17883,Robin Vega,F,9th,Bailey High School,84,64
17884,17884,Stephanie Robbins,F,10th,Bailey High School,87,56
17885,17885,Joseph Webster,M,11th,Bailey High School,68,69
17886,17886,David Harper,M,10th,Bailey High School,97,60
17887,17887,Michaela Morgan,F,10th,Bailey High School,74,74
17888,17888,Jeffrey Sherman,M,12th,Bailey High School,93,57
17889,17889,Zachary Williams,M,12th,Bailey High School,77,89
17890,17890,Debra Owen,F,11th,Bailey High School,92,77
17891,17891,Devin Phillips,M,12th,Bailey High School,69,83
17892,17892,Kenneth Juarez,M,9th,Bailey High School,96,69
17893,17893,Jennifer Martin,F,11th,Bailey High School,86,92
17894,17894,Katie Ingram,F,11th,Bailey High School,73,83
17895,17895,Laura Castillo,F,10th,Bailey High School,78,71
17896,17896,Jessica Butler,F,12th,Bailey High School,78,91
17897,17897,Daniel Thomas,M,12th,Bailey High School,65,69
17898,17898,Alan Hall,M,12th,Bailey High School,86,71
17899,17899,Robin Castillo,F,11th,Bailey High School,81,86
17900,17900,Ashley Bowman,F,12th,Bailey High School,75,63
...,...,...,...,...,...,...,...
22817,22817,Rhonda Ferguson,F,9th,Bailey High School,92,81
22818,22818,Brenda Dixon,F,9th,Bailey High School,84,82
22819,22819,Danny Cummings,M,11th,Bailey High School,89,72
22820,22820,Steven Fischer,M,12th,Bailey High School,87,73
22821,22821,Kenneth Brooks,M,9th,Bailey High School,93,93
22822,22822,Tyler Smith,M,9th,Bailey High School,75,88
22823,22823,Brian Li,M,10th,Bailey High School,92,85
22824,22824,Rebecca Harris,F,10th,Bailey High School,87,82
22825,22825,Renee Spence,F,11th,Bailey High School,96,59
22826,22826,Benjamin Silva,M,10th,Bailey High School,77,63
22827,22827,Alison Anderson,F,9th,Bailey High School,87,68
22828,22828,Bethany Harvey,F,9th,Bailey High School,69,59
22829,22829,Rodney Miller,M,12th,Bailey High School,94,69
22830,22830,Nicholas Costa,M,9th,Bailey High School,81,86
22831,22831,Samuel Blair,M,10th,Bailey High School,87,82
22832,22832,Kimberly Bennett,F,11th,Bailey High School,85,63
22833,22833,Ronald Baker,M,12th,Bailey High School,97,88
22834,22834,Brittany Gates,F,11th,Bailey High School,85,60
22835,22835,Katherine Steele,F,11th,Bailey High School,71,81
22836,22836,Caleb Hernandez,M,12th,Bailey High School,66,62
22837,22837,Ryan Allen,M,9th,Bailey High School,98,63
22838,22838,Robert Miller,M,11th,Bailey High School,99,57
22839,22839,Rodney Thompson,M,10th,Bailey High School,79,88
22840,22840,Sarah Rivera,F,11th,Bailey High School,95,68
22841,22841,Lauren Miller,F,10th,Bailey High School,96,86
22842,22842,Jaclyn Ayala,F,12th,Bailey High School,74,93
22843,22843,Jennifer Tapia,F,12th,Bailey High School,79,56
22844,22844,Gabriel Ashley,M,9th,Bailey High School,95,88
22845,22845,Sarah Cooper,F,10th,Bailey High School,91,62
22846,22846,Dr. Nicholas Garcia,M,11th,Bailey High School,90,79

In [639]:
Holden = students_df.loc[students_df['school'] == "Holden High School",:].copy()
Holden

,Student ID,name,gender,grade,school,reading_score,math_score
22847,22847,Daniel Rodriguez,M,11th,Holden High School,86,92
22848,22848,Bryan Perkins,M,9th,Holden High School,91,81
22849,22849,Scott Holder,M,9th,Holden High School,98,93
22850,22850,Troy Jackson,M,11th,Holden High School,80,90
22851,22851,William Gomez,M,9th,Holden High School,76,85
22852,22852,Lance Lindsey,M,9th,Holden High School,91,99
22853,22853,Alice Hernandez,F,11th,Holden High School,86,69
22854,22854,Nicole Baldwin,F,11th,Holden High School,89,98
22855,22855,Shelly Robertson,F,9th,Holden High School,96,79
22856,22856,Anthony Jackson,M,9th,Holden High School,89,89
22857,22857,Darren Gross,M,11th,Holden High School,97,86
22858,22858,Stephanie Jennings,F,10th,Holden High School,85,84
22859,22859,Shawn Nguyen,M,12th,Holden High School,94,95
22860,22860,John Espinoza,M,10th,Holden High School,93,80
22861,22861,Lisa Rodriguez,F,11th,Holden High School,81,97
22862,22862,Nicholas Ward,M,11th,Holden High School,91,97
22863,22863,Alexander Bailey,M,9th,Holden High School,75,69
22864,22864,Debra Garcia,F,12th,Holden High School,87,69
22865,22865,Karen Roberts,F,11th,Holden High School,90,94
22866,22866,Tara Williams,F,9th,Holden High School,93,80
22867,22867,Charles Hernandez,M,10th,Holden High School,91,81
22868,22868,Ashley Anderson,F,12th,Holden High School,94,75
22869,22869,Jonathan Jones,M,11th,Holden High School,91,70
22870,22870,Nicole Smith,F,9th,Holden High School,70,78
22871,22871,Megan Carr,F,11th,Holden High School,88,74
22872,22872,Jonathan Lopez,M,10th,Holden High School,84,78
22873,22873,Craig Barnes,M,12th,Holden High School,75,80
22874,22874,Monica Harrington,F,10th,Holden High School,93,82
22875,22875,Grant Thomas,M,11th,Holden High School,72,80
22876,22876,Timothy Smith,M,10th,Holden High School,81,78
...,...,...,...,...,...,...,...
23244,23244,David Krause,M,11th,Holden High School,78,99
23245,23245,Christopher Cox,M,9th,Holden High School,82,88
23246,23246,Ruth Myers,F,11th,Holden High School,81,95
23247,23247,Jennifer Weber,F,12th,Holden High School,73,79
23248,23248,Nathan Graham,M,10th,Holden High School,91,95
23249,23249,Michael Boyer,M,10th,Holden High School,69,82
23250,23250,Cassandra Rodriguez,F,11th,Holden High School,71,99
23251,23251,Angela Richardson,F,10th,Holden High School,93,74
23252,23252,Erica Harris,F,11th,Holden High School,75,95
23253,23253,Elizabeth Golden,F,9th,Holden High School,74,96
23254,23254,Tim Nash,M,10th,Holden High School,73,99
23255,23255,Jennifer Cantrell,F,10th,Holden High School,74,69
23256,23256,Rachel Hodge,F,10th,Holden High School,76,89
23257,23257,Denise Nguyen,F,9th,Holden High School,90,69
23258,23258,Robert Harris,M,12th,Holden High School,92,92
23259,23259,Samuel Shelton,M,10th,Holden High School,72,89
23260,23260,Michael Brown,M,10th,Holden High School,81,86
23261,23261,Lisa Evans,F,10th,Holden High School,86,89
23262,23262,Paula Robles,F,9th,Holden High School,70,85
23263,23263,Bailey Velazquez,F,11th,Holden High School,72,85
23264,23264,Dean Stewart,M,10th,Holden High School,88,99
23265,23265,James Williams,M,9th,Holden High School,95,77
23266,23266,Alexander Thomas,M,9th,Holden High School,80,72
23267,23267,Chris Mcbride,M,9th,Holden High School,92,95
23268,23268,Mikayla Ortiz,F,12th,Holden High School,85,73
23269,23269,Sharon Douglas,F,9th,Holden High School,78,93
23270,23270,Lauren Little,F,9th,Holden High School,94,95
23271,23271,Christine Kaufman,F,9th,Holden High School,83,95
23272,23272,Christina Smith,F,11th,Holden High School,94,84
23273,23273,Joyce Martin,F,10th,Holden High School,77,92

In [640]:
Pena = students_df.loc[students_df['school'] == "Pena High School",:].copy()
Pena

,Student ID,name,gender,grade,school,reading_score,math_score
23274,23274,Alec Davis,M,9th,Pena High School,91,75
23275,23275,Michael Meyer,M,10th,Pena High School,94,76
23276,23276,Donald Gutierrez,M,11th,Pena High School,98,91
23277,23277,Travis Chavez,M,11th,Pena High School,78,71
23278,23278,Sheena Ball,F,12th,Pena High School,87,92
23279,23279,Jenna Weaver,F,9th,Pena High School,76,84
23280,23280,Richard Alexander,M,11th,Pena High School,73,97
23281,23281,Chris Underwood,M,12th,Pena High School,69,72
23282,23282,Jacqueline Hebert,F,12th,Pena High School,69,88
23283,23283,Cheyenne Garcia,F,11th,Pena High School,86,86
23284,23284,Lance Davis,M,12th,Pena High School,69,77
23285,23285,Joshua Johnston,M,9th,Pena High School,94,93
23286,23286,Laura Hamilton,F,10th,Pena High School,87,88
23287,23287,Kayla Medina,F,11th,Pena High School,75,99
23288,23288,Justin Taylor,M,9th,Pena High School,69,92
23289,23289,Jacqueline Thornton,F,10th,Pena High School,94,83
23290,23290,Eric Wright,M,11th,Pena High School,69,94
23291,23291,Evan Beard,M,11th,Pena High School,98,88
23292,23292,Derrick Green,M,11th,Pena High School,69,82
23293,23293,Laurie Moore DDS,F,12th,Pena High School,96,95
23294,23294,Pamela Riley,F,9th,Pena High School,77,88
23295,23295,Jennifer Jackson,F,10th,Pena High School,92,96
23296,23296,Jason Thompson,M,9th,Pena High School,94,92
23297,23297,Brent Villegas,M,9th,Pena High School,97,77
23298,23298,Breanna Howell,F,10th,Pena High School,71,97
23299,23299,Shaun Jennings,M,10th,Pena High School,89,93
23300,23300,Margaret Barnes,F,9th,Pena High School,72,75
23301,23301,Caitlin Perkins,F,9th,Pena High School,94,98
23302,23302,Jeffery Brown,M,11th,Pena High School,84,75
23303,23303,Gary Henderson,M,11th,Pena High School,79,84
...,...,...,...,...,...,...,...
24206,24206,Bobby Gilbert,M,12th,Pena High School,99,99
24207,24207,David Snyder,M,11th,Pena High School,79,70
24208,24208,Mrs. Wendy Gomez DVM,F,11th,Pena High School,81,94
24209,24209,Kenneth Ware,M,10th,Pena High School,74,81
24210,24210,Kara Stuart MD,F,11th,Pena High School,69,79
24211,24211,Julie Tran,F,9th,Pena High School,86,72
24212,24212,Ryan Dougherty,M,10th,Pena High School,90,92
24213,24213,Catherine Davis,F,11th,Pena High School,79,99
24214,24214,Joshua Holloway,M,10th,Pena High School,88,80
24215,24215,Albert Pennington,M,9th,Pena High School,96,95
24216,24216,Maria Oconnor,F,10th,Pena High School,98,90
24217,24217,Megan Park,F,12th,Pena High School,84,78
24218,24218,Charlotte Jones,F,11th,Pena High School,79,71
24219,24219,Sandra Smith,F,12th,Pena High School,92,79
24220,24220,Grace Riggs,F,9th,Pena High School,70,84
24221,24221,Amy Wang,F,11th,Pena High School,75,81
24222,24222,Abigail Lucas,F,10th,Pena High School,74,84
24223,24223,Victoria Lewis,F,12th,Pena High School,77,77
24224,24224,Karina Simmons,F,12th,Pena High School,78,77
24225,24225,Kiara Brown,F,10th,Pena High School,70,73
24226,24226,Thomas Reid,M,11th,Pena High School,88,97
24227,24227,Sue Ewing,F,11th,Pena High School,78,82
24228,24228,George Molina,M,11th,Pena High School,99,80
24229,24229,Catherine Brennan,F,9th,Pena High School,92,74
24230,24230,Mark Gonzalez,M,10th,Pena High School,70,90
24231,24231,Crystal Pennington,F,12th,Pena High School,84,76
24232,24232,Christina Jones,F,10th,Pena High School,69,84
24233,24233,John Kennedy,M,9th,Pena High School,79,82
24234,24234,Amanda Mendoza,F,11th,Pena High School,79,69
24235,24235,Nathaniel Hodge,M,12th,Pena High School,99,96

In [641]:
Wright = students_df.loc[students_df['school'] == "Wright High School",:].copy()
Wright

,Student ID,name,gender,grade,school,reading_score,math_score
24236,24236,Aaron Johnson,M,10th,Wright High School,89,72
24237,24237,Kimberly Hamilton,F,10th,Wright High School,84,93
24238,24238,Ashley Johns,F,10th,Wright High School,88,88
24239,24239,Stephanie Donovan,F,10th,Wright High School,75,84
24240,24240,Cynthia Guzman,F,11th,Wright High School,93,82
24241,24241,Mario Daniel,M,10th,Wright High School,85,86
24242,24242,Debbie Perry,F,11th,Wright High School,81,72
24243,24243,Anthony Weiss,M,10th,Wright High School,95,74
24244,24244,Amy Hanna,F,11th,Wright High School,95,78
24245,24245,Eric Espinoza,M,9th,Wright High School,86,74
24246,24246,Melanie Thomas,F,10th,Wright High School,80,96
24247,24247,Shannon Barajas,F,10th,Wright High School,75,92
24248,24248,Randy Wright,M,10th,Wright High School,72,89
24249,24249,Allison Mcpherson,F,11th,Wright High School,93,82
24250,24250,Christopher Newton,M,9th,Wright High School,82,76
24251,24251,Andrea Singh,F,10th,Wright High School,90,77
24252,24252,Jeffrey Dyer,M,12th,Wright High School,87,72
24253,24253,Phillip Martinez,M,10th,Wright High School,97,91
24254,24254,Brandon Cantrell,M,10th,Wright High School,84,90
24255,24255,Theresa Wilson,F,10th,Wright High School,72,83
24256,24256,Sierra Martinez,F,9th,Wright High School,86,86
24257,24257,Travis Hall,M,10th,Wright High School,87,96
24258,24258,Megan Huber,F,12th,Wright High School,99,90
24259,24259,Brian Kemp,M,11th,Wright High School,85,79
24260,24260,Aaron Warner,M,10th,Wright High School,72,99
24261,24261,Judy King,F,9th,Wright High School,78,99
24262,24262,Christopher Beck,M,10th,Wright High School,71,98
24263,24263,Zachary Cox,M,12th,Wright High School,99,82
24264,24264,Thomas Lopez,M,12th,Wright High School,94,91
24265,24265,Nicholas Ayala,M,10th,Wright High School,82,81
...,...,...,...,...,...,...,...
26006,26006,Alexis Gonzalez,F,11th,Wright High School,88,70
26007,26007,James Blankenship,M,10th,Wright High School,85,90
26008,26008,Mark Roberts,M,11th,Wright High School,87,95
26009,26009,Matthew Jackson,M,10th,Wright High School,81,94
26010,26010,Sarah Hernandez,F,10th,Wright High School,89,98
26011,26011,Brittney Nolan,F,11th,Wright High School,70,76
26012,26012,Dennis Carter,M,11th,Wright High School,99,84
26013,26013,Shane Robinson,M,9th,Wright High School,92,92
26014,26014,Julie Knight,F,9th,Wright High School,92,85
26015,26015,Carol Watson,F,10th,Wright High School,91,75
26016,26016,Tom Wallace,M,12th,Wright High School,90,90
26017,26017,Brandon Mitchell,M,9th,Wright High School,76,81
26018,26018,Brian Lopez,M,9th,Wright High School,79,91
26019,26019,Mark Walters,M,11th,Wright High School,92,92
26020,26020,Helen Morgan,F,12th,Wright High School,94,84
26021,26021,Danielle Klein,F,12th,Wright High School,79,86
26022,26022,David Mendez,M,10th,Wright High School,90,90
26023,26023,Jeremiah Patel,M,9th,Wright High School,87,97
26024,26024,Belinda Higgins,F,12th,Wright High School,85,91
26025,26025,Amber Bender,F,12th,Wright High School,91,78
26026,26026,Crystal Smith,F,11th,Wright High School,72,76
26027,26027,Michael Washington,M,9th,Wright High School,97,88
26028,26028,Christina Goodman,F,11th,Wright High School,94,69
26029,26029,Natalie Howard,F,12th,Wright High School,80,93
26030,26030,William Richardson,M,9th,Wright High School,90,77
26031,26031,Lauren Duncan,F,12th,Wright High School,90,82
26032,26032,Heather Stuart,F,11th,Wright High School,94,95
26033,26033,Elizabeth Robbins,F,12th,Wright High School,69,99
26034,26034,John Mann,M,11th,Wright High School,73,91
26035,26035,Michael Holmes,M,9th,Wright High School,98,80

In [642]:
Rod = students_df.loc[students_df['school'] == "Rodriguez High School",:].copy()
Rod

,Student ID,name,gender,grade,school,reading_score,math_score
26036,26036,Sherry Jenkins,F,11th,Rodriguez High School,74,81
26037,26037,Kimberly Calderon,F,10th,Rodriguez High School,80,86
26038,26038,William Brady,M,11th,Rodriguez High School,97,62
26039,26039,Jacob Padilla,M,11th,Rodriguez High School,79,73
26040,26040,Paula Maldonado,F,10th,Rodriguez High School,96,92
26041,26041,Patricia Escobar,F,12th,Rodriguez High School,68,98
26042,26042,Becky Castillo,F,11th,Rodriguez High School,93,61
26043,26043,Tamara Morris,F,10th,Rodriguez High School,63,98
26044,26044,Brian Smith,M,9th,Rodriguez High School,67,97
26045,26045,Katelyn Valencia,F,12th,Rodriguez High School,92,61
26046,26046,Gary Orr,M,9th,Rodriguez High School,89,60
26047,26047,Melissa Lowery,F,9th,Rodriguez High School,85,92
26048,26048,Brian Moore,M,12th,Rodriguez High School,66,99
26049,26049,Nicole Simon,F,10th,Rodriguez High School,76,72
26050,26050,Tiffany Smith,F,9th,Rodriguez High School,91,87
26051,26051,Christopher Black,M,11th,Rodriguez High School,83,74
26052,26052,Richard Gonzalez,M,10th,Rodriguez High School,99,55
26053,26053,Cameron Hawkins,M,10th,Rodriguez High School,87,89
26054,26054,Desiree Martinez,F,11th,Rodriguez High School,73,91
26055,26055,Robert Shepard,M,11th,Rodriguez High School,65,65
26056,26056,Tina Campbell,F,12th,Rodriguez High School,83,86
26057,26057,Debra Ashley,F,10th,Rodriguez High School,95,74
26058,26058,Cody Wilson,M,11th,Rodriguez High School,77,55
26059,26059,Michelle Wall,F,9th,Rodriguez High School,91,70
26060,26060,Jon Reyes,M,12th,Rodriguez High School,69,99
26061,26061,Sarah Young DDS,F,12th,Rodriguez High School,83,96
26062,26062,David Martin,M,11th,Rodriguez High School,88,55
26063,26063,Lauren Weber,F,11th,Rodriguez High School,92,75
26064,26064,Matthew Henderson,M,12th,Rodriguez High School,94,61
26065,26065,Micheal Ryan,M,12th,Rodriguez High School,68,69
...,...,...,...,...,...,...,...
30005,30005,Brenda Contreras,F,10th,Rodriguez High School,78,62
30006,30006,Michael Ross,M,12th,Rodriguez High School,82,75
30007,30007,Mark Gonzalez,M,9th,Rodriguez High School,82,63
30008,30008,Jennifer Nichols,F,9th,Rodriguez High School,67,90
30009,30009,Andrew Andrews,M,10th,Rodriguez High School,74,84
30010,30010,David Carter,M,11th,Rodriguez High School,91,82
30011,30011,Jennifer Acosta,F,11th,Rodriguez High School,76,59
30012,30012,William Williams,M,12th,Rodriguez High School,82,93
30013,30013,Taylor Hayes,F,10th,Rodriguez High School,85,81
30014,30014,Samuel Delgado,M,11th,Rodriguez High School,70,90
30015,30015,Anthony Smith,M,11th,Rodriguez High School,78,96
30016,30016,Jessica Smith,F,11th,Rodriguez High School,95,84
30017,30017,Francisco Brewer,M,9th,Rodriguez High School,72,92
30018,30018,Adam Watson,M,9th,Rodriguez High School,75,61
30019,30019,Mr. Justin Mccoy,M,12th,Rodriguez High School,87,63
30020,30020,Benjamin Martinez,M,9th,Rodriguez High School,80,67
30021,30021,Heather Rush,F,9th,Rodriguez High School,77,97
30022,30022,Bobby Evans,M,10th,Rodriguez High School,70,66
30023,30023,Richard Black,M,11th,Rodriguez High School,97,84
30024,30024,Julia Woodard,F,11th,Rodriguez High School,75,60
30025,30025,Samantha Santana,F,10th,Rodriguez High School,67,85
30026,30026,Kathryn Morris,F,11th,Rodriguez High School,96,72
30027,30027,Sara Smith,F,12th,Rodriguez High School,84,85
30028,30028,Kelly Hamilton,F,9th,Rodriguez High School,85,72
30029,30029,Patrick Hopkins,M,10th,Rodriguez High School,85,88
30030,30030,Gina Blevins,F,12th,Rodriguez High School,76,62
30031,30031,Shannon Mack,F,9th,Rodriguez High School,87,93
30032,30032,Hayley Snyder,F,12th,Rodriguez High School,97,79
30033,30033,Kayla Ruiz,F,10th,Rodriguez High School,76,62
30034,30034,Andrew Clark,M,10th,Rodriguez High School,90,95

In [643]:
John = students_df.loc[students_df['school'] == "Johnson High School",:].copy()
John

,Student ID,name,gender,grade,school,reading_score,math_score
30035,30035,Lisa Casey,F,12th,Johnson High School,87,87
30036,30036,Jessica Lopez,F,9th,Johnson High School,98,62
30037,30037,Anna Wilkins,F,11th,Johnson High School,89,77
30038,30038,Andrew Smith,M,9th,Johnson High School,66,85
30039,30039,Robert Allison,M,11th,Johnson High School,63,85
30040,30040,Andrew Wilson,M,11th,Johnson High School,70,84
30041,30041,Kevin Odonnell,M,9th,Johnson High School,77,73
30042,30042,Courtney Ramirez,F,10th,Johnson High School,98,58
30043,30043,Walter Turner,M,9th,Johnson High School,79,80
30044,30044,Kayla Day,F,11th,Johnson High School,81,56
30045,30045,Tamara Mitchell,F,12th,Johnson High School,63,56
30046,30046,Martin Hudson,M,12th,Johnson High School,70,88
30047,30047,Shawn Black,M,12th,Johnson High School,67,89
30048,30048,Samantha Bailey,F,10th,Johnson High School,75,56
30049,30049,Robert Nguyen DDS,M,11th,Johnson High School,73,66
30050,30050,Joshua Robertson,M,12th,Johnson High School,74,92
30051,30051,Daniel Ochoa,M,9th,Johnson High School,67,73
30052,30052,Patrick Fritz,M,9th,Johnson High School,90,79
30053,30053,Melanie Johnson,F,9th,Johnson High School,92,71
30054,30054,Adam Townsend,M,11th,Johnson High School,75,64
30055,30055,Anita Cobb,F,9th,Johnson High School,74,91
30056,30056,Cody Day,M,10th,Johnson High School,75,67
30057,30057,Wendy Hale,F,12th,Johnson High School,84,93
30058,30058,Rachel Baker,F,11th,Johnson High School,81,95
30059,30059,Austin Clayton,M,10th,Johnson High School,89,62
30060,30060,John Carney,M,10th,Johnson High School,79,96
30061,30061,Michael Williams,M,9th,Johnson High School,78,85
30062,30062,Christopher Mays,M,12th,Johnson High School,86,81
30063,30063,Emily Carter,F,12th,Johnson High School,86,95
30064,30064,Leonard Roberts Jr.,M,9th,Johnson High School,77,76
...,...,...,...,...,...,...,...
34766,34766,William Duran,M,9th,Johnson High School,86,84
34767,34767,James Henderson,M,11th,Johnson High School,91,89
34768,34768,Angela Brooks,F,9th,Johnson High School,88,61
34769,34769,Stephen Huynh,M,9th,Johnson High School,82,81
34770,34770,Brandon Mason,M,10th,Johnson High School,76,60
34771,34771,Erika Koch,F,11th,Johnson High School,91,74
34772,34772,Jason Martinez,M,9th,Johnson High School,67,87
34773,34773,Bradley Gibson,M,9th,Johnson High School,81,90
34774,34774,Logan Miller,M,11th,Johnson High School,81,57
34775,34775,Stacy Reynolds,F,10th,Johnson High School,81,63
34776,34776,Morgan Jacobs,F,11th,Johnson High School,99,98
34777,34777,Brianna Wheeler,F,10th,Johnson High School,77,93
34778,34778,Derrick Hutchinson,M,11th,Johnson High School,81,72
34779,34779,Stephen Jones,M,11th,Johnson High School,99,67
34780,34780,Amanda Rocha,F,9th,Johnson High School,76,86
34781,34781,John Saunders,M,11th,Johnson High School,81,57
34782,34782,Ian Thompson,M,11th,Johnson High School,80,95
34783,34783,Carl Martinez,M,10th,Johnson High School,69,91
34784,34784,Jeremiah Kramer,M,12th,Johnson High School,90,59
34785,34785,Dana Jimenez,F,10th,Johnson High School,77,76
34786,34786,Matthew Jones,M,9th,Johnson High School,74,79
34787,34787,Shelby Anderson,F,11th,Johnson High School,90,65
34788,34788,Michael Lang,M,10th,Johnson High School,81,89
34789,34789,Charles Molina,M,10th,Johnson High School,84,59
34790,34790,Sheila Grant,F,10th,Johnson High School,82,61
34791,34791,Miranda Vincent,F,9th,Johnson High School,92,64
34792,34792,Joshua Murphy,M,9th,Johnson High School,91,70
34793,34793,Alicia Cantu,F,11th,Johnson High School,68,78
34794,34794,Robert Taylor,M,11th,Johnson High School,80,71
34795,34795,Adriana Brown,F,9th,Johnson High School,97,68

In [644]:
Ford = students_df.loc[students_df['school'] == "Ford High School",:].copy()
Ford

,Student ID,name,gender,grade,school,reading_score,math_score
34796,34796,Michael Mercado,M,9th,Ford High School,66,94
34797,34797,Stephen Wolf,M,11th,Ford High School,68,63
34798,34798,Bonnie Hughes,F,12th,Ford High School,73,59
34799,34799,Melissa Smith,F,11th,Ford High School,88,58
34800,34800,Brian Mitchell,M,10th,Ford High School,96,55
34801,34801,Mr. William Scott,M,9th,Ford High School,73,75
34802,34802,Stephen Taylor,M,11th,Ford High School,82,59
34803,34803,Steven Lee,M,9th,Ford High School,77,84
34804,34804,Candace Campbell,F,11th,Ford High School,80,67
34805,34805,Veronica English,F,9th,Ford High School,75,93
34806,34806,Crystal Sandoval,F,11th,Ford High School,85,84
34807,34807,Christopher Garcia,M,9th,Ford High School,96,93
34808,34808,Tamara Daniels,F,12th,Ford High School,84,94
34809,34809,Jeffrey Mcclure,M,11th,Ford High School,89,84
34810,34810,Debra White,F,11th,Ford High School,98,81
34811,34811,Michael Williams,M,9th,Ford High School,71,56
34812,34812,Donald Davis,M,11th,Ford High School,67,89
34813,34813,Jodi Johnson,F,11th,Ford High School,91,88
34814,34814,Martin Molina,M,11th,Ford High School,69,76
34815,34815,Donald Taylor,M,11th,Ford High School,82,92
34816,34816,Emma Adams,F,9th,Ford High School,88,85
34817,34817,Julia Garcia,F,12th,Ford High School,87,82
34818,34818,John Jones,M,9th,Ford High School,95,81
34819,34819,Nicholas Doyle,M,12th,Ford High School,87,98
34820,34820,Diana Nguyen,F,10th,Ford High School,98,95
34821,34821,Amy Baker,F,9th,Ford High School,93,76
34822,34822,Christopher Scott,M,12th,Ford High School,97,84
34823,34823,Teresa Campbell,F,9th,Ford High School,94,78
34824,34824,Sherri Williams,F,9th,Ford High School,84,89
34825,34825,Jason Craig,M,11th,Ford High School,65,83
...,...,...,...,...,...,...,...
37505,37505,Jason Wagner,M,12th,Ford High School,97,80
37506,37506,Maurice Nielsen,M,12th,Ford High School,76,66
37507,37507,James Turner,M,12th,Ford High School,73,74
37508,37508,Larry Pope,M,9th,Ford High School,74,61
37509,37509,Robert Martin,M,12th,Ford High School,80,67
37510,37510,Darius Jimenez,M,12th,Ford High School,89,82
37511,37511,Daniel Turner,M,10th,Ford High School,68,58
37512,37512,Lauren Cook,F,9th,Ford High School,84,72
37513,37513,Wayne Washington,M,11th,Ford High School,79,63
37514,37514,Leslie White,F,12th,Ford High School,80,73
37515,37515,Maria Andrade,F,12th,Ford High School,69,87
37516,37516,Tracy Sanchez,F,11th,Ford High School,76,75
37517,37517,Kayla Johnson,F,9th,Ford High School,71,80
37518,37518,Daniel Andrews,M,9th,Ford High School,89,98
37519,37519,Ruben Ramirez,M,12th,Ford High School,84,65
37520,37520,Benjamin Odonnell,M,11th,Ford High School,63,74
37521,37521,Meredith Tapia,F,9th,Ford High School,77,78
37522,37522,Ricky Little,M,12th,Ford High School,90,68
37523,37523,Rebecca Valenzuela,F,10th,Ford High School,90,84
37524,37524,Carrie Fletcher,F,9th,Ford High School,84,72
37525,37525,Steven Summers,M,9th,Ford High School,71,71
37526,37526,Jon Santiago,M,10th,Ford High School,98,56
37527,37527,Thomas Christensen,M,9th,Ford High School,98,60
37528,37528,Nicholas Perry,M,11th,Ford High School,83,83
37529,37529,Victoria Rodriguez,F,11th,Ford High School,76,69
37530,37530,William Rivera,M,9th,Ford High School,63,59
37531,37531,Bernard Reid,M,9th,Ford High School,94,80
37532,37532,Dawn Sawyer,F,12th,Ford High School,91,66
37533,37533,Thomas Knapp,M,12th,Ford High School,75,70
37534,37534,Melissa Porter,F,9th,Ford High School,76,84

In [645]:
Thom = students_df.loc[students_df['school'] == "Thomas High School",:].copy()
Thom

,Student ID,name,gender,grade,school,reading_score,math_score
37535,37535,Norma Mata,F,10th,Thomas High School,76,76
37536,37536,Cody Miller,M,11th,Thomas High School,84,82
37537,37537,Erik Snyder,M,9th,Thomas High School,80,90
37538,37538,Tanya Martinez,F,9th,Thomas High School,71,69
37539,37539,Noah Erickson,M,9th,Thomas High School,86,76
37540,37540,Austin Meyer,M,9th,Thomas High School,73,96
37541,37541,Eric Stevens,M,10th,Thomas High School,80,76
37542,37542,Elizabeth Bennett,F,11th,Thomas High School,91,94
37543,37543,Madison Hampton,F,9th,Thomas High School,82,73
37544,37544,Jacqueline Harris,F,10th,Thomas High School,71,92
37545,37545,Christopher Shaw,M,10th,Thomas High School,84,68
37546,37546,Steven Hoover MD,M,12th,Thomas High School,90,81
37547,37547,Amanda Hicks,F,12th,Thomas High School,77,74
37548,37548,Brian Moss,M,10th,Thomas High School,70,97
37549,37549,Christopher Martinez,M,11th,Thomas High School,70,68
37550,37550,Patricia Diaz,F,9th,Thomas High School,76,99
37551,37551,Nancy Mason,F,12th,Thomas High School,91,86
37552,37552,Matthew Marquez,M,10th,Thomas High School,88,79
37553,37553,Curtis Gibson,M,10th,Thomas High School,97,70
37554,37554,Rebecca Brown,F,11th,Thomas High School,76,77
37555,37555,Chad Martin,M,11th,Thomas High School,72,82
37556,37556,Sarah Park,F,11th,Thomas High School,95,74
37557,37557,Shannon Sanchez,F,11th,Thomas High School,93,84
37558,37558,Kelly Henderson,M,9th,Thomas High School,81,90
37559,37559,Kiara Bates,F,9th,Thomas High School,72,98
37560,37560,Kim Hall,F,11th,Thomas High School,70,83
37561,37561,Charles Lopez,M,11th,Thomas High School,69,93
37562,37562,Teresa Johns,F,9th,Thomas High School,86,69
37563,37563,Amy Richard,F,10th,Thomas High School,80,97
37564,37564,Stephen Patrick,M,9th,Thomas High School,93,97
...,...,...,...,...,...,...,...
39140,39140,Cheyenne Hernandez,F,9th,Thomas High School,76,99
39141,39141,Jonathan Sullivan,M,10th,Thomas High School,86,93
39142,39142,Deborah Higgins DDS,F,10th,Thomas High School,96,83
39143,39143,Steven Jackson,M,11th,Thomas High School,71,93
39144,39144,Cristian Webster,M,12th,Thomas High School,77,87
39145,39145,Audrey Fry,F,10th,Thomas High School,94,74
39146,39146,Michael Carroll,M,9th,Thomas High School,69,95
39147,39147,Raymond Hawkins,M,10th,Thomas High School,88,81
39148,39148,Christopher Wilson,M,10th,Thomas High School,89,89
39149,39149,Glenda Fletcher,F,11th,Thomas High School,82,93
39150,39150,Jennifer Hamilton,F,11th,Thomas High School,80,75
39151,39151,Shannon Williams,F,10th,Thomas High School,84,73
39152,39152,Lori Moore,F,9th,Thomas High School,98,84
39153,39153,William Hubbard,M,9th,Thomas High School,80,75
39154,39154,Bradley Johnson,M,12th,Thomas High School,91,71
39155,39155,John Brooks,M,10th,Thomas High School,92,98
39156,39156,Stephanie Contreras,F,11th,Thomas High School,79,95
39157,39157,Kristen Gonzalez,F,9th,Thomas High School,79,94
39158,39158,Kari Holloway,F,10th,Thomas High School,87,90
39159,39159,Kimberly Cabrera,F,11th,Thomas High School,85,72
39160,39160,Katie Weaver,F,11th,Thomas High School,89,86
39161,39161,April Reyes,F,10th,Thomas High School,70,84
39162,39162,Derek Weeks,M,12th,Thomas High School,94,77
39163,39163,John Reese,M,11th,Thomas High School,90,75
39164,39164,Joseph Anthony,M,9th,Thomas High School,97,76
39165,39165,Donna Howard,F,12th,Thomas High School,99,90
39166,39166,Dawn Bell,F,10th,Thomas High School,95,70
39167,39167,Rebecca Tanner,F,9th,Thomas High School,73,84
39168,39168,Desiree Kidd,F,10th,Thomas High School,99,90
39169,39169,Carolyn Jackson,F,11th,Thomas High School,95,75

In [646]:
HMath = Huang['math_score'].mean()
FigMath = Fig['math_score'].mean()
SheltonMath = Shelton['math_score'].mean()
HernMath = Hern['math_score'].mean()
GriffinMath = Griff['math_score'].mean()
WilsonMath = Wilson['math_score'].mean()
CabMath = Cab['math_score'].mean()
BaileyMath = Bailey['math_score'].mean()
HoldenMath = Holden['math_score'].mean()
PenaMath = Pena['math_score'].mean()
WrightMath = Wright['math_score'].mean()
RodMath = Rod['math_score'].mean()
JohnMath = John['math_score'].mean()
FordMath = Ford['math_score'].mean()
ThomMath = Thom['math_score'].mean()

In [647]:
all_math_avg = [HMath, FigMath, SheltonMath, HernMath, GriffinMath, WilsonMath, CabMath, BaileyMath, HoldenMath, PenaMath, WrightMath, RodMath, JohnMath, FordMath, ThomMath]

In [648]:
all_math_avg

[76.62941378128214,
 76.71176670057646,
 83.3594548551959,
 77.28975188781014,
 83.35149863760218,
 83.2742006132282,
 83.06189451022605,
 77.04843247588424,
 83.80327868852459,
 83.83991683991684,
 83.68222222222222,
 76.84271067766942,
 77.07246376811594,
 77.10259218692954,
 83.4183486238532]

In [649]:
HRead = Huang['reading_score'].mean()
FigRead = Fig['reading_score'].mean()
SheltonRead = Shelton['reading_score'].mean()
HernRead = Hern['reading_score'].mean()
GriffinRead = Griff['reading_score'].mean()
WilsonRead = Wilson['reading_score'].mean()
CabRead = Cab['reading_score'].mean()
BaileyRead = Bailey['reading_score'].mean()
HoldenRead = Holden['reading_score'].mean()
PenaRead = Pena['reading_score'].mean()
WrightRead = Wright['reading_score'].mean()
RodRead = Rod['reading_score'].mean()
JohnRead = John['reading_score'].mean()
FordRead = Ford['reading_score'].mean()
ThomRead = Thom['reading_score'].mean()

In [650]:
all_read_avg = [HRead, FigRead, SheltonRead, HernRead, GriffinRead, WilsonRead, CabRead, BaileyRead, HoldenRead, PenaRead, WrightRead, RodRead, JohnRead, FordRead, ThomRead]

In [651]:
HMathPa = Huang[(Huang['math_score']>=60)]
HMathP = HMathPa["name"].count()
FigMathPa = Fig[(Fig['math_score']>=60)]
SheltonMathPa = Shelton[(Shelton['math_score']>=60)]
HernMathPa = Hern[(Hern['math_score']>=60)]
GriffinMathPa = Griff[(Griff['math_score']>=60)]
WilsonMathPa = Wilson[(Wilson['math_score']>=60)]
CabMathPa = Cab[(Cab['math_score']>=60)]
BaileyMathPa = Bailey[(Bailey['math_score']>=60)]
HoldenMathPa = Holden[(Holden['math_score']>=60)]
PenaMathPa = Pena[(Pena['math_score']>=60)]
WrightMathPa = Wright[(Wright['math_score']>=60)]
RodMathPa = Rod[(Rod['math_score']>=60)]
JohnMathPa = John[(John['math_score']>=60)]
FordMathPa = Ford[(Ford['math_score']>=60)]
ThomMathPa = Thom[(Thom['math_score']>=60)]

FigMathP = FigMathPa["name"].count()
SheltonMathP = SheltonMathPa["name"].count()
HernMathP = HernMathPa["name"].count()
GriffinMathP = GriffinMathPa["name"].count()
WilsonMathP = WilsonMathPa["name"].count()
CabMathP = CabMathPa["name"].count()
BaileyMathP = BaileyMathPa["name"].count()
HoldenMathP = HoldenMathPa["name"].count()
PenaMathP = PenaMathPa["name"].count()
WrightMathP = WrightMathPa["name"].count()
RodMathP = RodMathPa["name"].count()
JohnMathP = JohnMathPa["name"].count()
FordMathP = FordMathPa["name"].count()
ThomMathP = ThomMathPa["name"].count()
all_pass_math = [HMathP, FigMathP, SheltonMathP, HernMathP, GriffinMathP, WilsonMathP, CabMathP, BaileyMathP, HoldenMathP, PenaMathP, WrightMathP, RodMathP, JohnMathP, FordMathP, ThomMathP]

all_pass_math

[2592,
 2608,
 1761,
 4129,
 1468,
 2283,
 1858,
 4455,
 427,
 962,
 1800,
 3541,
 4246,
 2446,
 1635]

In [652]:
HReadPa = Huang[(Huang['reading_score']>=60)]
HReadP = HReadPa["name"].count()
FigReadPa = Fig[(Fig['reading_score']>=60)]
SheltonReadPa = Shelton[(Shelton['reading_score']>=60)]
HernReadPa = Hern[(Hern['reading_score']>=60)]
GriffinReadPa = Griff[(Griff['reading_score']>=60)]
WilsonReadPa = Wilson[(Wilson['reading_score']>=60)]
CabReadPa = Cab[(Cab['reading_score']>=60)]
BaileyReadPa = Bailey[(Bailey['reading_score']>=60)]
HoldenReadPa = Holden[(Holden['reading_score']>=60)]
PenaReadPa = Pena[(Pena['reading_score']>=60)]
WrightReadPa = Wright[(Wright['reading_score']>=60)]
RodReadPa = Rod[(Rod['reading_score']>=60)]
JohnReadPa = John[(John['reading_score']>=60)]
FordReadPa = Ford[(Ford['reading_score']>=60)]
ThomReadPa = Thom[(Thom['reading_score']>=60)]

FigReadP = FigReadPa["name"].count()
SheltonReadP = SheltonReadPa["name"].count()
HernReadP = HernReadPa["name"].count()
GriffinReadP = GriffinReadPa["name"].count()
WilsonReadP = WilsonReadPa["name"].count()
CabReadP = CabReadPa["name"].count()
BaileyReadP = BaileyReadPa["name"].count()
HoldenReadP = HoldenReadPa["name"].count()
PenaReadP = PenaReadPa["name"].count()
WrightReadP = WrightReadPa["name"].count()
RodReadP = RodReadPa["name"].count()
JohnReadP = JohnReadPa["name"].count()
FordReadP = FordReadPa["name"].count()
ThomReadP = ThomReadPa["name"].count()
all_pass_read = [HReadP, FigReadP, SheltonReadP, HernReadP, GriffinReadP, WilsonReadP, CabReadP, BaileyReadP, HoldenReadP, PenaReadP, WrightReadP, RodReadP, JohnReadP, FordReadP, ThomReadP]

all_pass_read

[2917,
 2949,
 1761,
 4635,
 1468,
 2283,
 1858,
 4976,
 427,
 962,
 1800,
 3999,
 4761,
 2739,
 1635]

In [653]:

HOM = HMathPa["name"].count()
FigOM = FigMathPa["name"].count()
SheltonOM = SheltonMathPa["name"].count()
HernOM = HernMathPa["name"].count()
GriffinOM = GriffinMathPa["name"].count()
WilsonOM = WilsonMathPa["name"].count()
CabOM = CabMathPa["name"].count()
BaileyOM = BaileyMathPa["name"].count()
HoldenOM = HoldenMathPa["name"].count()
PenaOM = PenaMathPa["name"].count()
WrightOM = WrightMathPa["name"].count()
RodOM = RodMathPa["name"].count()
JohnOM = JohnMathPa["name"].count()
FordOM = FordMathPa["name"].count()
ThomOM = ThomMathPa["name"].count()
OMPass = [HOM, FigOM, SheltonOM, HernOM, GriffinOM, WilsonOM, CabOM, BaileyOM, HoldenOM, PenaOM, WrightOM, RodOM, JohnOM, FordOM, ThomOM]


HReadPO = HReadPa["name"].count()
FigReadPO = FigReadPa["name"].count()
SheltonReadPO = SheltonReadPa["name"].count()
HernReadPO = HernReadPa["name"].count()
GriffinReadPO = GriffinReadPa["name"].count()
WilsonReadPO = WilsonReadPa["name"].count()
CabReadPO = CabReadPa["name"].count()
BaileyReadPO = BaileyReadPa["name"].count()
HoldenReadPO = HoldenReadPa["name"].count()
PenaReadPO = PenaReadPa["name"].count()
WrightReadPO = WrightReadPa["name"].count()
RodReadPO = RodReadPa["name"].count()
JohnReadPO = JohnReadPa["name"].count()
FordReadPO = FordReadPa["name"].count()
ThomReadPO = ThomReadPa["name"].count()
ORPass = [HReadPO, FigReadPO, SheltonReadPO, HernReadPO, GriffinReadPO, WilsonReadPO, CabReadPO, BaileyReadPO, HoldenReadPO, PenaReadPO, WrightReadPO, RodReadPO, JohnReadPO, FordReadPO, ThomReadPO]

Overa = OMPass/All_Schools['size'] 
Overb = ORPass/All_Schools['size']
Overc = ((Overa + Overb)/2)*100
Overc

0      94.429208
1      94.218379
2     100.000000
3      94.541532
4     100.000000
5     100.000000
6     100.000000
7      94.764871
8     100.000000
9     100.000000
10    100.000000
11     94.273568
12     94.591472
13     94.651333
14    100.000000
Name: size, dtype: float64

In [654]:
#per_student_budget = (total_school_budget/students_by_school_df)
#per_student_budget
ss_titles = ["School Type", "Total Students", "Total School Budget", "Per Student Budget", "Average Math Score", "Average Reading Score", "% Passing Math", "% Passing Reading", "% Overall Passing Rate"]
ss_info = {"School Type": [school_type]}
#School_summary = pd.DataFrame(index=[school_names],columns=[ss_titles])
All_Schools = pd.DataFrame(schools_df)
All_Schools["Per Student Budget"] = All_Schools['budget']/All_Schools['size']
All_Schools["Average Math Score"] = all_math_avg
All_Schools["Average Math Score"] = All_Schools["Average Math Score"].map("{:,.2f}".format)
All_Schools["Per Student Budget"] = All_Schools["Per Student Budget"].map("{:,.2f}".format)
All_Schools["Average Reading Score"] = all_read_avg
All_Schools["Average Reading Score"] = All_Schools["Average Reading Score"].map("{:,.2f}".format)
All_Schools["% Passing Math"] = (all_pass_math/All_Schools['size'])*100
All_Schools["% Passing Math"] = All_Schools["% Passing Math"].map("{:,.2f}".format)
All_Schools["% Passing Reading"] = (all_pass_read/All_Schools['size'])*100
All_Schools["% Passing Reading"] = All_Schools["% Passing Reading"].map("{:,.2f}".format)

All_Schools["Overall Passing Rate"] = Overc

All_Schools["Overall Passing Rate"] = All_Schools["Overall Passing Rate"].map("{:,.2f}".format)
All_Schools

,School ID,name,type,size,budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
0,0,Huang High School,District,2917,1910635,655.00,76.63,81.18,88.86,100.00,94.43
1,1,Figueroa High School,District,2949,1884411,639.00,76.71,81.16,88.44,100.00,94.22
2,2,Shelton High School,Charter,1761,1056600,600.00,83.36,83.73,100.00,100.00,100.00
3,3,Hernandez High School,District,4635,3022020,652.00,77.29,80.93,89.08,100.00,94.54
4,4,Griffin High School,Charter,1468,917500,625.00,83.35,83.82,100.00,100.00,100.00
5,5,Wilson High School,Charter,2283,1319574,578.00,83.27,83.99,100.00,100.00,100.00
6,6,Cabrera High School,Charter,1858,1081356,582.00,83.06,83.98,100.00,100.00,100.00
7,7,Bailey High School,District,4976,3124928,628.00,77.05,81.03,89.53,100.00,94.76
8,8,Holden High School,Charter,427,248087,581.00,83.80,83.81,100.00,100.00,100.00
9,9,Pena High School,Charter,962,585858,609.00,83.84,84.04,100.00,100.00,100.00
10,10,Wright High School,Charter,1800,1049400,583.00,83.68,83.95,100.00,100.00,100.00
11,11,Rodriguez High School,District,3999,2547363,637.00,76.84,80.74,88.55,100.00,94.27
12,12,Johnson High School,District,4761,3094650,650.00,77.07,80.97,89.18,100.00,94.59
13,13,Ford High School,District,2739,1763916,644.00,77.10,80.75,89.30,100.00,94.65
14,14,Thomas High School,Charter,1635,1043130,638.00,83.42,83.85,100.00,100.00,100.00

In [655]:
School_Summary = All_Schools

In [656]:
School_Summary

,School ID,name,type,size,budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
0,0,Huang High School,District,2917,1910635,655.00,76.63,81.18,88.86,100.00,94.43
1,1,Figueroa High School,District,2949,1884411,639.00,76.71,81.16,88.44,100.00,94.22
2,2,Shelton High School,Charter,1761,1056600,600.00,83.36,83.73,100.00,100.00,100.00
3,3,Hernandez High School,District,4635,3022020,652.00,77.29,80.93,89.08,100.00,94.54
4,4,Griffin High School,Charter,1468,917500,625.00,83.35,83.82,100.00,100.00,100.00
5,5,Wilson High School,Charter,2283,1319574,578.00,83.27,83.99,100.00,100.00,100.00
6,6,Cabrera High School,Charter,1858,1081356,582.00,83.06,83.98,100.00,100.00,100.00
7,7,Bailey High School,District,4976,3124928,628.00,77.05,81.03,89.53,100.00,94.76
8,8,Holden High School,Charter,427,248087,581.00,83.80,83.81,100.00,100.00,100.00
9,9,Pena High School,Charter,962,585858,609.00,83.84,84.04,100.00,100.00,100.00
10,10,Wright High School,Charter,1800,1049400,583.00,83.68,83.95,100.00,100.00,100.00
11,11,Rodriguez High School,District,3999,2547363,637.00,76.84,80.74,88.55,100.00,94.27
12,12,Johnson High School,District,4761,3094650,650.00,77.07,80.97,89.18,100.00,94.59
13,13,Ford High School,District,2739,1763916,644.00,77.10,80.75,89.30,100.00,94.65
14,14,Thomas High School,Charter,1635,1043130,638.00,83.42,83.85,100.00,100.00,100.00

In [700]:
School_Summary = School_Summary.rename(columns={"size" : "Total Students"})
School_Summary = School_Summary.rename(columns={"name" : "School Name"})
School_Summary = School_Summary.rename(columns={"budget" : "Total School Budget"})
School_Summary = School_Summary.rename(columns={"type" : "School Type"})
School_Summary = School_Summary.drop("School ID",1)
School_Summary

ValueError: labels ['School ID'] not contained in axis

In [701]:
School_Summary

,School Name,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
0,Huang High School,District,2917,1910635,655.00,76.63,81.18,88.86,100.00,94.43
1,Figueroa High School,District,2949,1884411,639.00,76.71,81.16,88.44,100.00,94.22
2,Shelton High School,Charter,1761,1056600,600.00,83.36,83.73,100.00,100.00,100.00
3,Hernandez High School,District,4635,3022020,652.00,77.29,80.93,89.08,100.00,94.54
4,Griffin High School,Charter,1468,917500,625.00,83.35,83.82,100.00,100.00,100.00
5,Wilson High School,Charter,2283,1319574,578.00,83.27,83.99,100.00,100.00,100.00
6,Cabrera High School,Charter,1858,1081356,582.00,83.06,83.98,100.00,100.00,100.00
7,Bailey High School,District,4976,3124928,628.00,77.05,81.03,89.53,100.00,94.76
8,Holden High School,Charter,427,248087,581.00,83.80,83.81,100.00,100.00,100.00
9,Pena High School,Charter,962,585858,609.00,83.84,84.04,100.00,100.00,100.00
10,Wright High School,Charter,1800,1049400,583.00,83.68,83.95,100.00,100.00,100.00
11,Rodriguez High School,District,3999,2547363,637.00,76.84,80.74,88.55,100.00,94.27
12,Johnson High School,District,4761,3094650,650.00,77.07,80.97,89.18,100.00,94.59
13,Ford High School,District,2739,1763916,644.00,77.10,80.75,89.30,100.00,94.65
14,Thomas High School,Charter,1635,1043130,638.00,83.42,83.85,100.00,100.00,100.00

In [702]:
#Top_Peform = School_Summary[(School_Summary['% Passing Reading']==100) & (School_Summary['% Passing Math']==100)] 
#Top_Perform.head()
Top_Perform = School_Summary.sort_values('Average Math Score', ascending=False)
Top_Perform_5 = Top_Perform.head(5)
Top_Perform_5

,School Name,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
9,Pena High School,Charter,962,585858,609.00,83.84,84.04,100.00,100.00,100.00
8,Holden High School,Charter,427,248087,581.00,83.80,83.81,100.00,100.00,100.00
10,Wright High School,Charter,1800,1049400,583.00,83.68,83.95,100.00,100.00,100.00
14,Thomas High School,Charter,1635,1043130,638.00,83.42,83.85,100.00,100.00,100.00
2,Shelton High School,Charter,1761,1056600,600.00,83.36,83.73,100.00,100.00,100.00

In [703]:
Bottom = School_Summary.sort_values('Overall Passing Rate', ascending=False)
Bottom_5 = Bottom.head(5)
Bottom_5

,School Name,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
7,Bailey High School,District,4976,3124928,628.00,77.05,81.03,89.53,100.00,94.76
13,Ford High School,District,2739,1763916,644.00,77.10,80.75,89.30,100.00,94.65
12,Johnson High School,District,4761,3094650,650.00,77.07,80.97,89.18,100.00,94.59
3,Hernandez High School,District,4635,3022020,652.00,77.29,80.93,89.08,100.00,94.54
0,Huang High School,District,2917,1910635,655.00,76.63,81.18,88.86,100.00,94.43

In [704]:
Grades = students_df["grade"].value_counts()

In [858]:
Data_frame = students_df[["school","grade","reading_score"]]
Huang_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Huang High School")]
#mHuang_grade9 = Huang_grade9.median()
Fig_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Figueroa High School")]
Shelton_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Shelton High School")]
Hernandez_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Hernandez High School")]
Griffin_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Griffin High School")]
Wilson_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Wilson High School")]
Cab_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Cabrera High School")]
Bailey_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Bailey High School")]
Holden_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Holden High School")]
Pena_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Pena High School")]
Wright_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Wright High School")]
Rod_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Rodriguez High School")]
John_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Johnson High School")]
Ford_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Ford High School")]
Thomas_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Thomas High School")]


Huang_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Huang High School")]
Fig_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Figueroa High School")]
Shelton_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Shelton High School")]
Hernandez_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Hernandez High School")]
Griffin_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Griffin High School")]
Wilson_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Wilson High School")]
Cab_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Cabrera High School")]
Bailey_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Bailey High School")]
Holden_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Holden High School")]
Pena_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Pena High School")]
Wright_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Wright High School")]
Rod_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Rodriguez High School")]
John_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Johnson High School")]
Ford_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Ford High School")]
Thomas_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Thomas High School")]



Huang_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Huang High School")]
Fig_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Figueroa High School")]
Shelton_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Shelton High School")]
Hernandez_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Hernandez High School")]
Griffin_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Griffin High School")]
Wilson_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Wilson High School")]
Cab_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Cabrera High School")]
Bailey_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Bailey High School")]
Holden_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Holden High School")]
Pena_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Pena High School")]
Wright_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Wright High School")]
Rod_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Rodriguez High School")]
John_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Johnson High School")]
Ford_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Ford High School")]
Thomas_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Thomas High School")]

Huang_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Huang High School")]
Fig_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Figueroa High School")]
Shelton_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Shelton High School")]
Hernandez_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Hernandez High School")]
Griffin_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Griffin High School")]
Wilson_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Wilson High School")]
Cab_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Cabrera High School")]
Bailey_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Bailey High School")]
Holden_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Holden High School")]
Pena_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Pena High School")]
Wright_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Wright High School")]
Rod_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Rodriguez High School")]
John_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Johnson High School")]
Ford_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Ford High School")]
Thomas_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Thomas High School")]

#grade9 = [(Huang_grade9), Fig_grade9, Shelton_grade9, Hernandez_grade9, Griffin_grade9, Wilson_grade9, Cab_grade9, Bailey_grade9, Holden_grade9, Pena_grade9, Wright_grade9, Rod_grade9, John_grade9, Ford_grade9, Thomas_grade9]
MHuang_grade9 = Huang_grade9['reading_score'].median()
MFig_grade9 = Fig_grade9['reading_score'].median()
MShelton_grade9 = Shelton_grade9['reading_score'].median()
MHernandez_grade9 = Hernandez_grade9['reading_score'].median()
MGriffin_grade9 = Griffin_grade9['reading_score'].median()
MWilson_grade9 = Wilson_grade9['reading_score'].median()
MCab_grade9 = Cab_grade9['reading_score'].median()
MBailey_grade9 = Bailey_grade9['reading_score'].median()
MHolden_grade9 = Holden_grade9['reading_score'].median()
MPena_grade9 = Pena_grade9['reading_score'].median()
MWright_grade9 = Wright_grade9['reading_score'].median()
MRod_grade9 = Rod_grade9['reading_score'].median()
MJohn_grade9 = John_grade9['reading_score'].median()
MFord_grade9 = Ford_grade9['reading_score'].median()
MThomas_grade9 = Thomas_grade9['reading_score'].median()

MHuang_grade10 = Huang_grade10['reading_score'].median()
MFig_grade10 = Fig_grade10['reading_score'].median()
MShelton_grade10 = Shelton_grade10['reading_score'].median()
MHernandez_grade10 = Hernandez_grade10['reading_score'].median()
MGriffin_grade10 = Griffin_grade10['reading_score'].median()
MWilson_grade10 = Wilson_grade10['reading_score'].median()
MCab_grade10 = Cab_grade10['reading_score'].median()
MBailey_grade10 = Bailey_grade10['reading_score'].median()
MHolden_grade10 = Holden_grade10['reading_score'].median()
MPena_grade10 = Pena_grade10['reading_score'].median()
MWright_grade10 = Wright_grade10['reading_score'].median()
MRod_grade10 = Rod_grade10['reading_score'].median()
MJohn_grade10 = John_grade10['reading_score'].median()
MFord_grade10 = Ford_grade10['reading_score'].median()
MThomas_grade10 = Thomas_grade10['reading_score'].median()

MHuang_grade11 = Huang_grade11['reading_score'].median()
MFig_grade11 = Fig_grade11['reading_score'].median()
MShelton_grade11 = Shelton_grade11['reading_score'].median()
MHernandez_grade11 = Hernandez_grade11['reading_score'].median()
MGriffin_grade11 = Griffin_grade11['reading_score'].median()
MWilson_grade11 = Wilson_grade11['reading_score'].median()
MCab_grade11 = Cab_grade11['reading_score'].median()
MBailey_grade11 = Bailey_grade11['reading_score'].median()
MHolden_grade11 = Holden_grade11['reading_score'].median()
MPena_grade11 = Pena_grade11['reading_score'].median()
MWright_grade11 = Wright_grade11['reading_score'].median()
MRod_grade11 = Rod_grade11['reading_score'].median()
MJohn_grade11 = John_grade11['reading_score'].median()
MFord_grade11 = Ford_grade11['reading_score'].median()
MThomas_grade11 = Thomas_grade11['reading_score'].median()

MHuang_grade12 = Huang_grade12['reading_score'].median()
MFig_grade12 = Fig_grade12['reading_score'].median()
MShelton_grade12 = Shelton_grade12['reading_score'].median()
MHernandez_grade12 = Hernandez_grade12['reading_score'].median()
MGriffin_grade12 = Griffin_grade12['reading_score'].median()
MWilson_grade12 = Wilson_grade12['reading_score'].median()
MCab_grade12 = Cab_grade12['reading_score'].median()
MBailey_grade12 = Bailey_grade12['reading_score'].median()
MHolden_grade12 = Holden_grade12['reading_score'].median()
MPena_grade12 = Pena_grade12['reading_score'].median()
MWright_grade12 = Wright_grade12['reading_score'].median()
MRod_grade12 = Rod_grade12['reading_score'].median()
MJohn_grade12 = John_grade12['reading_score'].median()
MFord_grade12 = Ford_grade12['reading_score'].median()
MThomas_grade12 = Thomas_grade12['reading_score'].median()

grade9 = [MHuang_grade9, MFig_grade9, MShelton_grade9, MHernandez_grade9, MGriffin_grade9, MWilson_grade9, MCab_grade9, MBailey_grade9, MHolden_grade9, MPena_grade9, MWright_grade9, MRod_grade9, MJohn_grade9, MFord_grade9, MThomas_grade9]
grade10 = [MHuang_grade10, MFig_grade10, MShelton_grade10, MHernandez_grade10, MGriffin_grade10, MWilson_grade10, MCab_grade10, MBailey_grade10, MHolden_grade10, MPena_grade10, MWright_grade10, MRod_grade10, MJohn_grade10, MFord_grade10, MThomas_grade10]
grade11 = [MHuang_grade11, MFig_grade11, MShelton_grade11, MHernandez_grade11, MGriffin_grade11, MWilson_grade11, MCab_grade11, MBailey_grade11, MHolden_grade11, MPena_grade11, MWright_grade11, MRod_grade11, MJohn_grade11, MFord_grade11, MThomas_grade11]
grade12 = [MHuang_grade12, MFig_grade12, MShelton_grade12, MHernandez_grade12, MGriffin_grade12, MWilson_grade12, MCab_grade12, MBailey_grade12, MHolden_grade12, MPena_grade12, MWright_grade12, MRod_grade12, MJohn_grade12, MFord_grade12, MThomas_grade12]


grade_df = pd.DataFrame({'School Name': ["Huang High School", "Figueroa High School", "Shelton High School", "Hernandez High School", "Griffin High School", "Wilson High School", "Cabrera High School", "Bailey High School", "Holden High School", "Pena High School", "Wright High School", "Rodriguez High School", "Johnson High School", "Ford High School", "Thomas High School"]})
grade_df["9th"] = grade9
grade_df["9th"] = grade_df["9th"].map("{:,.2f}".format)
grade_df["10th"] = grade10
grade_df["10th"] = grade_df["10th"].map("{:,.2f}".format)
grade_df["11th"] = grade11
grade_df["11th"] = grade_df["11th"].map("{:,.2f}".format)
grade_df["12th"] = grade12
grade_df["12th"] = grade_df["12th"].map("{:,.2f}".format)

grade_df

              School Name    9th   10th   11th   12th
0       Huang High School  82.00  82.00  82.00  80.00
1    Figueroa High School  81.00  82.00  81.00  82.00
2     Shelton High School  84.00  83.00  85.50  82.00
3   Hernandez High School  81.00  80.00  82.00  81.00
4     Griffin High School  83.00  84.00  84.00  84.00
5      Wilson High School  84.00  84.00  84.00  84.00
6     Cabrera High School  84.00  84.00  83.50  85.00
7      Bailey High School  82.00  81.00  81.00  81.00
8      Holden High School  83.00  84.00  84.00  85.00
9        Pena High School  84.00  84.00  84.00  85.00
10     Wright High School  84.00  84.00  85.00  84.00
11  Rodriguez High School  81.00  81.00  81.00  80.00
12    Johnson High School  81.00  81.00  80.00  81.00
13       Ford High School  81.00  82.00  81.00  81.00
14     Thomas High School  83.00  85.00  83.00  85.00

In [866]:
Data_frame = students_df[["school","grade","math_score"]]
rHuang_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Huang High School")]
#mHuang_grade9 = Huang_grade9.median()
rFig_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Figueroa High School")]
rShelton_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Shelton High School")]
rHernandez_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Hernandez High School")]
rGriffin_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Griffin High School")]
rWilson_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Wilson High School")]
rCab_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Cabrera High School")]
rBailey_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Bailey High School")]
rHolden_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Holden High School")]
rPena_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Pena High School")]
rWright_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Wright High School")]
rRod_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Rodriguez High School")]
rJohn_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Johnson High School")]
rFord_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Ford High School")]
rThomas_grade9 = Data_frame[(Data_frame["grade"] == "9th") & (Data_frame["school"] == "Thomas High School")]


rHuang_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Huang High School")]
rFig_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Figueroa High School")]
rShelton_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Shelton High School")]
rHernandez_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Hernandez High School")]
rGriffin_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Griffin High School")]
rWilson_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Wilson High School")]
rCab_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Cabrera High School")]
rBailey_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Bailey High School")]
rHolden_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Holden High School")]
rPena_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Pena High School")]
rWright_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Wright High School")]
rRod_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Rodriguez High School")]
rJohn_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Johnson High School")]
rFord_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Ford High School")]
rThomas_grade10 = Data_frame[(Data_frame["grade"] == "10th") & (Data_frame["school"] == "Thomas High School")]



rHuang_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Huang High School")]
rFig_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Figueroa High School")]
rShelton_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Shelton High School")]
rHernandez_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Hernandez High School")]
rGriffin_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Griffin High School")]
rWilson_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Wilson High School")]
rCab_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Cabrera High School")]
rBailey_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Bailey High School")]
rHolden_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Holden High School")]
rPena_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Pena High School")]
rWright_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Wright High School")]
rRod_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Rodriguez High School")]
rJohn_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Johnson High School")]
rFord_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Ford High School")]
rThomas_grade11 = Data_frame[(Data_frame["grade"] == "11th") & (Data_frame["school"] == "Thomas High School")]

rHuang_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Huang High School")]
rFig_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Figueroa High School")]
rShelton_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Shelton High School")]
rHernandez_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Hernandez High School")]
rGriffin_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Griffin High School")]
rWilson_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Wilson High School")]
rCab_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Cabrera High School")]
rBailey_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Bailey High School")]
rHolden_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Holden High School")]
rPena_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Pena High School")]
rWright_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Wright High School")]
rRod_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Rodriguez High School")]
rJohn_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Johnson High School")]
rFord_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Ford High School")]
rThomas_grade12 = Data_frame[(Data_frame["grade"] == "12th") & (Data_frame["school"] == "Thomas High School")]

#grade9 = [(Huang_grade9), Fig_grade9, Shelton_grade9, Hernandez_grade9, Griffin_grade9, Wilson_grade9, Cab_grade9, Bailey_grade9, Holden_grade9, Pena_grade9, Wright_grade9, Rod_grade9, John_grade9, Ford_grade9, Thomas_grade9]
rrHuang_grade9 = rHuang_grade9['math_score'].median()
rrFig_grade9 = rFig_grade9['math_score'].median()
rrShelton_grade9 = rShelton_grade9['math_score'].median()
rrHernandez_grade9 = rHernandez_grade9['math_score'].median()
rrGriffin_grade9 = rGriffin_grade9['math_score'].median()
rrWilson_grade9 = rWilson_grade9['math_score'].median()
rrCab_grade9 = rCab_grade9['math_score'].median()
rrBailey_grade9 = rBailey_grade9['math_score'].median()
rrHolden_grade9 = rHolden_grade9['math_score'].median()
rrPena_grade9 = rPena_grade9['math_score'].median()
rrWright_grade9 = rWright_grade9['math_score'].median()
rrRod_grade9 = rRod_grade9['math_score'].median()
rrJohn_grade9 = rJohn_grade9['math_score'].median()
rrFord_grade9 = rFord_grade9['math_score'].median()
rrThomas_grade9 = rThomas_grade9['math_score'].median()

rrHuang_grade10 = rHuang_grade10['math_score'].median()
rrFig_grade10 = rFig_grade10['math_score'].median()
rrShelton_grade10 = rShelton_grade10['math_score'].median()
rrHernandez_grade10 = rHernandez_grade10['math_score'].median()
rrGriffin_grade10 = rGriffin_grade10['math_score'].median()
rrWilson_grade10 = rWilson_grade10['math_score'].median()
rrCab_grade10 = rCab_grade10['math_score'].median()
rrBailey_grade10 = rBailey_grade10['math_score'].median()
rrHolden_grade10 = rHolden_grade10['math_score'].median()
rrPena_grade10 = rPena_grade10['math_score'].median()
rrWright_grade10 = rWright_grade10['math_score'].median()
rrRod_grade10 = rRod_grade10['math_score'].median()
rrJohn_grade10 = rJohn_grade10['math_score'].median()
rrFord_grade10 = rFord_grade10['math_score'].median()
rrThomas_grade10 = rThomas_grade10['math_score'].median()

rrHuang_grade11 = rHuang_grade11['math_score'].median()
rrFig_grade11 = rFig_grade11['math_score'].median()
rrShelton_grade11 = rShelton_grade11['math_score'].median()
rrHernandez_grade11 = rHernandez_grade11['math_score'].median()
rrGriffin_grade11 = rGriffin_grade11['math_score'].median()
rrWilson_grade11 = rWilson_grade11['math_score'].median()
rrCab_grade11 = rCab_grade11['math_score'].median()
rrBailey_grade11 = rBailey_grade11['math_score'].median()
rrHolden_grade11 = rHolden_grade11['math_score'].median()
rrPena_grade11 = rPena_grade11['math_score'].median()
rrWright_grade11 = rWright_grade11['math_score'].median()
rrRod_grade11 = rRod_grade11['math_score'].median()
rrJohn_grade11 = rJohn_grade11['math_score'].median()
rrFord_grade11 = rFord_grade11['math_score'].median()
rrThomas_grade11 = rThomas_grade11['math_score'].median()

rrHuang_grade12 = rHuang_grade12['math_score'].median()
rrFig_grade12 = rFig_grade12['math_score'].median()
rrShelton_grade12 = rShelton_grade12['math_score'].median()
rrHernandez_grade12 = rHernandez_grade12['math_score'].median()
rrGriffin_grade12 = rGriffin_grade12['math_score'].median()
rrWilson_grade12 = rWilson_grade12['math_score'].median()
rrCab_grade12 = rCab_grade12['math_score'].median()
rrBailey_grade12 = rBailey_grade12['math_score'].median()
rrHolden_grade12 = rHolden_grade12['math_score'].median()
rrPena_grade12 = rPena_grade12['math_score'].median()
rrWright_grade12 = rWright_grade12['math_score'].median()
rrRod_grade12 = rRod_grade12['math_score'].median()
rrJohn_grade12 = rJohn_grade12['math_score'].median()
rrFord_grade12 = rFord_grade12['math_score'].median()
rrThomas_grade12 = rThomas_grade12['math_score'].median()

rrgrade9 = [rrHuang_grade9, rrFig_grade9, rrShelton_grade9, rrHernandez_grade9, rrGriffin_grade9, rrWilson_grade9, rrCab_grade9, rrBailey_grade9, rrHolden_grade9, rrPena_grade9, rrWright_grade9, rrRod_grade9, rrJohn_grade9, rrFord_grade9, rrThomas_grade9]
rrgrade10 = [rrHuang_grade10, rrFig_grade10, rrShelton_grade10, rrHernandez_grade10, rrGriffin_grade10, rrWilson_grade10, rrCab_grade10, rrBailey_grade10, rrHolden_grade10, rrPena_grade10, rrWright_grade10, rrRod_grade10, rrJohn_grade10, rrFord_grade10, rrThomas_grade10]
rrgrade11 = [rrHuang_grade11, rrFig_grade11, rrShelton_grade11, rrHernandez_grade11, rrGriffin_grade11, rrWilson_grade11, rrCab_grade11, rrBailey_grade11, rrHolden_grade11, rrPena_grade11, rrWright_grade11, rrRod_grade11, rrJohn_grade11, rrFord_grade11, rrThomas_grade11]
rrgrade12 = [rrHuang_grade12, rrFig_grade12, rrShelton_grade12, rrHernandez_grade12, rrGriffin_grade12, rrWilson_grade12, rrCab_grade12, rrBailey_grade12, rrHolden_grade12, rrPena_grade12, rrWright_grade12, rrRod_grade12, rrJohn_grade12, rrFord_grade12, rrThomas_grade12]


rrgrade_df = pd.DataFrame({'School Name': ["Huang High School", "Figueroa High School", "Shelton High School", "Hernandez High School", "Griffin High School", "Wilson High School", "Cabrera High School", "Bailey High School", "Holden High School", "Pena High School", "Wright High School", "Rodriguez High School", "Johnson High School", "Ford High School", "Thomas High School"]})
rrgrade_df["9th"] = grade9
rrgrade_df["9th"] = rrgrade_df["9th"].map("{:,.2f}".format)
rrgrade_df["10th"] = grade10
rrgrade_df["10th"] = rrgrade_df["10th"].map("{:,.2f}".format)
rrgrade_df["11th"] = grade11
rrgrade_df["11th"] = rrgrade_df["11th"].map("{:,.2f}".format)
rrgrade_df["12th"] = grade12
rrgrade_df["12th"] = rrgrade_df["12th"].map("{:,.2f}".format)

rrgrade_df

              School Name    9th   10th   11th   12th
0       Huang High School  82.00  82.00  82.00  80.00
1    Figueroa High School  81.00  82.00  81.00  82.00
2     Shelton High School  84.00  83.00  85.50  82.00
3   Hernandez High School  81.00  80.00  82.00  81.00
4     Griffin High School  83.00  84.00  84.00  84.00
5      Wilson High School  84.00  84.00  84.00  84.00
6     Cabrera High School  84.00  84.00  83.50  85.00
7      Bailey High School  82.00  81.00  81.00  81.00
8      Holden High School  83.00  84.00  84.00  85.00
9        Pena High School  84.00  84.00  84.00  85.00
10     Wright High School  84.00  84.00  85.00  84.00
11  Rodriguez High School  81.00  81.00  81.00  80.00
12    Johnson High School  81.00  81.00  80.00  81.00
13       Ford High School  81.00  82.00  81.00  81.00
14     Thomas High School  83.00  85.00  83.00  85.00

In [878]:
school_spending = School_Summary
school_spending = school_spending.drop("School Type",1)
school_spending["Spending Per Student"] = school_spending['Total School Budget']/ school_spending['Total Students']
school_spending = school_spending.drop("Total Students",1)
school_spending = school_spending.drop("Total School Budget",1)
school_spending = school_spending.drop("Per Student Budget",1)
school_spending

,School Name,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate,Spending Per Student
0,Huang High School,76.63,81.18,88.86,100.00,94.43,655.0
1,Figueroa High School,76.71,81.16,88.44,100.00,94.22,639.0
2,Shelton High School,83.36,83.73,100.00,100.00,100.00,600.0
3,Hernandez High School,77.29,80.93,89.08,100.00,94.54,652.0
4,Griffin High School,83.35,83.82,100.00,100.00,100.00,625.0
5,Wilson High School,83.27,83.99,100.00,100.00,100.00,578.0
6,Cabrera High School,83.06,83.98,100.00,100.00,100.00,582.0
7,Bailey High School,77.05,81.03,89.53,100.00,94.76,628.0
8,Holden High School,83.80,83.81,100.00,100.00,100.00,581.0
9,Pena High School,83.84,84.04,100.00,100.00,100.00,609.0
10,Wright High School,83.68,83.95,100.00,100.00,100.00,583.0
11,Rodriguez High School,76.84,80.74,88.55,100.00,94.27,637.0
12,Johnson High School,77.07,80.97,89.18,100.00,94.59,650.0
13,Ford High School,77.10,80.75,89.30,100.00,94.65,644.0
14,Thomas High School,83.42,83.85,100.00,100.00,100.00,638.0

In [911]:
school_sizes = School_Summary
school_sizes
max = school_sizes["Total Students"].max()
max
min = school_sizes["Total Students"].min()
min
#bins = [0, 3500, 5000]
#bin_labels = ["Small",  "Medium", "Large"]
#school_sizes["Total Students"] = school_sizes["Total Students"]

#pd.cut(school_sizes['Total Students'], bins, labels=bin_labels)
def size(c):
    if c['Total Students'] <= 1000:
        return 'Small'
    elif 1000 < c['Total Students'] <= 3500:
        return 'Medium'
    elif 3500 < c['Total Students'] <= 5000:
        return 'Large'
    else:
        return 'Undefined'
school_sizes['Size'] = school_sizes.apply(size, axis=1)
school_sizes

,School Name,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate,Size
0,Huang High School,District,2917,1910635,655.00,76.63,81.18,88.86,100.00,94.43,Medium
1,Figueroa High School,District,2949,1884411,639.00,76.71,81.16,88.44,100.00,94.22,Medium
2,Shelton High School,Charter,1761,1056600,600.00,83.36,83.73,100.00,100.00,100.00,Medium
3,Hernandez High School,District,4635,3022020,652.00,77.29,80.93,89.08,100.00,94.54,Large
4,Griffin High School,Charter,1468,917500,625.00,83.35,83.82,100.00,100.00,100.00,Medium
5,Wilson High School,Charter,2283,1319574,578.00,83.27,83.99,100.00,100.00,100.00,Medium
6,Cabrera High School,Charter,1858,1081356,582.00,83.06,83.98,100.00,100.00,100.00,Medium
7,Bailey High School,District,4976,3124928,628.00,77.05,81.03,89.53,100.00,94.76,Large
8,Holden High School,Charter,427,248087,581.00,83.80,83.81,100.00,100.00,100.00,Small
9,Pena High School,Charter,962,585858,609.00,83.84,84.04,100.00,100.00,100.00,Small
10,Wright High School,Charter,1800,1049400,583.00,83.68,83.95,100.00,100.00,100.00,Medium
11,Rodriguez High School,District,3999,2547363,637.00,76.84,80.74,88.55,100.00,94.27,Large
12,Johnson High School,District,4761,3094650,650.00,77.07,80.97,89.18,100.00,94.59,Large
13,Ford High School,District,2739,1763916,644.00,77.10,80.75,89.30,100.00,94.65,Medium
14,Thomas High School,Charter,1635,1043130,638.00,83.42,83.85,100.00,100.00,100.00,Medium